### ISSUE TITLE
Event buffering

### ISSUE THREAD

**Issue by shercoder** [adjust/android_sdk#106]
I am trying to understand `Event buffering`
https://github.com/adjust/android_sdk#15-enable-event-buffering

From what I understand from above documentation that `Adjust` batches all events into **one** request and send it after a minute. But that's not the behavior I am seeing, unless I am misreading the docs. I see that it waits 1 minute but it sends all events in their individual requests. For example, if there were 3 events occurred, then it will send 3 requests after a minute.

Please clarify. Thanks!

**Comment by wellle** [comment]
You are right, we are sending the batches in batches of individual requests. This should already reduce the connection overhead because we use keep-alive connections.

Putting the whole package queue into a single request adds a lot of complexity both to every SDK we have and the backend that needs to support it. Please let me know if and why you think that would be worth it.

**Comment by shercoder** [comment]
Ah ok. Thanks for clarifying. :+1:
