### ISSUE TITLE
Reporting revenue show doubled events

### ISSUE THREAD

**Issue by nzakharchenko** [adjust/android_sdk#110]
After updating SDK, I'm reporting revenue like shown in migrate manual:

```
AdjustEvent event = new AdjustEvent("abc123");
event.setRevenue(0.01, "EUR");
Adjust.trackEvent(event);
```

but after such changes, in dashboard I always see two events reported for one revenue. Is it some kind of bug? or it should be configured somehow?

**Comment by wellle** [comment]
@nzakharchenko: Could you enable verbose logging 
```java
config.setLogLevel(LogLevel.VERBOSE);
```
and do it again? If you manage to track a single event in the SDK and it shows up double in the dashboard again those log messages would be really helpful to investigate.

In order to not share you tokens publicly you can send those verbose logs to support@adjust.com. Mention in the mail that these logs should be forwarded to welle. Thanks!

**Comment by nzakharchenko** [comment]
@wellle done, send logs to support@adjust.com

**Comment by wellle** [comment]
Received. Will check check them.

**Comment by wellle** [comment]
I checked your logs but the event only shows up once in the dashboard, so everything worked as expected in this case. Please let me know if you manage to reproduce the issue where the dashboard shows different numbers than the SDK logs.

**Comment by nzakharchenko** [comment]
Looks like issue is fixed! Not sure what was the problem exactly, but trying with new tracker it works correctly. Thank you for support!
