### ISSUE TITLE
`dex` issue with `com.google.android.gms:play-services-ads`

### ISSUE THREAD

**Issue by kamoljan** [adjust/android_sdk#124]
Hi guys

During Adjust setup, can we skip the step [4](https://github.com/adjust/android_sdk#4-add-google-play-services)?

Even with `compile 'com.google.android.gms:play-services-ads:7.3.0'` it is causing `dex` issue.
Can we use `compile 'com.google.android.gms:play-services-base:7.3.0'` instead?

Best regards
Kamol

**Comment by uerceg** [comment]
Hi @kamoljan 

I don't think you should skip step 4 of our guide, since Google announced that if you're using tracking inside of app, you should have Google Play Services integrated in order to use advertising ID.

__As a reminder, please note that starting 1 August 2014, new apps and app updates distributed through Google Play must use the advertising ID in lieu of any other persistent identifiers for any advertising purposes, on devices that support the advertising ID.__

If you use `com.google.android.gms:play-services-base:7.3.0`, you still won't be able to use advertising ID which Google suggested in it's announcement, because that is the part of `-ads` package which is not part of `-base` package.

Thing which you maybe can try is to take original full Google Play Services library and try to strip it down by yourself, since I don't know if Google maybe left some unnecessary stuff in `-ads` package we maybe don't need for tracking. How to strip Google Play Services library is explained nicely in this article: https://medium.com/@rotxed/dex-skys-the-limit-no-65k-methods-is-28e6cb40cf71 in __Strip it till you make it__ part.

If you decide to strip the library on your own, you can test if you affected the tracking with this strip by running your app from Android Studio with VERBOSE log level and check after SDK is initialised if you see `gps_adid` property listed in debug output.

**Comment by kamoljan** [comment]
@uerceg thank you for your prompt response!
