### ISSUE TITLE
No Advertising ID with Play Services 7.5.0

### ISSUE THREAD

**Issue by tinsukE** [adjust/android_sdk#127]
When trying to upgrade the Play Services library to 7.5.0 (`compile 'com.google.android.gms:play-services-gcm:7.5.0'`), I've started getting the following error:
`Unable to get Google Play Services Advertising ID at start time`

Is the SDK v4.0.6 compatible with Play Services 7.5.0?

**Comment by uerceg** [comment]
Hi @tinsukE 

Thank you for writing us.

As far as I see, you are trying to integrate only Cloud Messaging part of Google Play Services (`com.google.android.gms:play-services-gcm:7.5.0`). In order to make our SDK work properly, you should integrate Google Mobile Ads as well (`com.google.android.gms:play-services-ads:7.5.0`).

Add `com.google.android.gms:play-services-ads:7.5.0` to your project and advertising ID should be there.

Feel free to write us if you still have problems with this issue.

Cheers
Ugi

**Comment by tinsukE** [comment]
Thanks for the quick feedback! And adding the play-services-ads dependency fixed my issue.
