### ISSUE TITLE
Is Adjust set up right?

### ISSUE THREAD

**Issue by HoangNHM** [adjust/android_sdk#145]
Hi,
I'm adding Adjust SDK to an Android project, follow the instruction [Here](https://github.com/adjust/android_sdk)
I use google_play_services_version: 6587000. 
I don't use Proguard.
In step 9 of the instruction, my LogCat does not show: 
`Install tracked`
, it shows:
`A/Adjust: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to production before publishing!`
`I/Adjust: Started subsession 10 of session 7`
And in dashboard, i see no info, already check “Switch to Sandbox”.
I don't know what wrong?
Thanks in advance!

**Comment by uerceg** [comment]
Hi @HoangNHM 

Reason you are not seeing `Install tracked` message is because you have started your app within your last session (session 7 in this case). Install is being tracked only when you start your app for the first time (session 1) and only initial session will be reported as install from our SDK.

Cheers

**Comment by HoangNHM** [comment]
Thank @uerceg, so my app & adjust SDK is working fine? Any possible reason why I cannot see information in the dashboard - in iOS version, I can see it.

**Comment by nonelse** [comment]
Hi @HoangNHM.

Maybe something went wrong with the first session in Android. You can retest by following the instruction on chapter 2.3 [`Testing attribution`](https://docs.adjust.com/en/getting-started/), that allows to forget the device on our server and simulate a fresh install.
One thing that might help see more detail is to configure the logger to `verbose` mode so you can see more detail.
For further support for your specific case, that isn't an issue directly with the SDK, you can also email us at support@adjust.com so the communication is more private if you wish so.

**Comment by HoangNHM** [comment]
Hi @nonelse,
Thank you for your fast reply, I will try it tomorrow.

**Comment by HoangNHM** [comment]
Hi,
Sorry for disturbing you with my problem, but I'm stuck. I used charlesproxy to view traffic, but I didn't see any adjust thing was sent out while running my app. My question is: is it wrong if nothing send to adjust (show in charlesproxy) while running app.
Thank you, I'm truly appreciated your help.

**Comment by nonelse** [comment]
Hi @HoangNHM .
I would suspect that the issue is with the proxy behaviour. By default, when they intercept a 5XX response, either don't forward it or change it somehow. The adjust sdk is expecting a reply with information even in a 500 status code response.
It's possible to see if the sdk is getting a response by testing in `sandbox` mode, with verbose logs. Each package send gets a `Response: ...` log and in the log it should contain a `message` parameter with the response information from the server, whether there is an error or not.
You should try to configure the proxy to forward traffic as is, or test without the proxy to see the messages.
We can be reached at support@adjust.com for more client oriented support than what can be done in github issues.
Thanks for reaching us!

**Comment by HoangNHM** [comment]
Thank you @nonelse,
After config device proxy, I can catch the adjust package in charlesproxy: https://app.adjust.com.
Dose it mean I'm setting adjust right, and should see log in DashBoard?

**Comment by nonelse** [comment]
You can see the logs in the device logs, either Android Studio or Xcode usually

**Comment by HoangNHM** [comment]
Thank you @nonelse , @uerceg ,
Problem was solved, adjust is now working fine. I retest the app.
