### ISSUE TITLE
Bundle proguard rules inside library

### ISSUE THREAD

**Issue by tmelz** [adjust/android_sdk#147]
The Android Gradle plugin supports bundling proguard rules as part of the library, so users won't need to manually add anything to their proguard files. This is great because users don't need to worry about keeping their file up to date.

Here's an example pull request showing the syntax--it's super easy!
https://github.com/koral--/android-gif-drawable/pull/193

**Comment by nonelse** [comment]
thanks @tmelz, we'll definitely look into it!

**Comment by tinsukE** [comment]
I see that Adjust is already using `consumerProguardFiles` in its [build.gradle](https://github.com/adjust/android_sdk/blob/master/Adjust/sdk-core/build.gradle).

The problem is that this embeds the proguard file only in the generated AAR:
https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.BuildType.html#com.android.build.gradle.internal.dsl.BuildType:consumerProguardFiles

And since the library is only available in JAR form, we can't benefit from the automatic Porguard rules yet:
http://repo1.maven.org/maven2/com/adjust/sdk/adjust-android/

@nonelse would Adjust be able to publish an AAR library too?

**Comment by ubuntudroid** [comment]
@uerceg Any news on the AAR front?

**Comment by uerceg** [comment]
👋 @ubuntudroid 

We're aiming to move to AAR format with our next major SDK version release. Hopefully in Q2. Stay tuned, will keep you posted in here.

**Comment by eugene-krivobokov** [comment]
Proguard rules can be bundled even into jar file: `src/main/resources/META-INF/proguard/your-config.pro`

Example: https://github.com/square/okhttp/blob/master/okhttp/src/main/resources/META-INF/proguard/okhttp3.pro

**Comment by auras** [comment]
7 years laster, still not using consumerProguardFiles?

**Comment by uerceg** [comment]
Hi @auras,

Indeed and definitely not one of the issues we are proud of. But believe it or not, this task is actually in progress on our end and we will start to bundle ProGuard rules soon. Most probably not with the next release which is aimed to go live somewhere next week, but the one after that.

Will definitely keep you posted and big sorry for everyone following this issue for such a huge delay on this one.

**Comment by uerceg** [comment]
Well, the day has finally come. As of [Android SDK v4.30.1](https://repo1.maven.org/maven2/com/adjust/sdk/adjust-android/4.30.1/), SDK is being shipped as an AAR archive into Maven repo. Thanks for everyone for the patience and one more time, apologies that it took quite a while for this ticket to be finally closed.

In case you encounter any issues with this version (or any other going forward), please feel free to comment / reopen.

Cheers!

**Comment by svenjacobs** [comment]
Hello,

Although artifacts have been shipped as AARs since 2022, they appear to still not include consumer ProGuard / R8 files. The [documentation](https://dev.adjust.com/en/sdk/android/v4/#set-up-proguard) still recommends manually adjusting the configuration. I'm kindly asking you to provide these configuration files in the archive. This would save us from the need to manually maintain the configuration, which can be error‑prone. This adjustment shouldn't be too complicated on your end and would greatly improve our workflow.

**Comment by shashanksu** [comment]
Hi @svenjacobs ,
Thanks for reaching out.  

The Adjust Android SDK AAR file (for example, [this](https://github.com/adjust/android_sdk/releases/download/v5.6.0/adjust-android-5.6.0.aar) one) already includes `proguard.txt` file with the required consumer ProGuard/R8 rules bundled inside the archive.  If your build setup is using the AAR, these rules should be picked up automatically.

The manual ProGuard steps in our documentation are only intended for projects that still integrate the SDK via the JAR distribution. We plan to remove or update that section of the documentation to avoid confusion going forward.

Hope this helps. If you have any other questions or notice anything unexpected, feel free to let us know.

Thanks again.

**Comment by svenjacobs** [comment]
Thank you very much for the clarification, @shashanksu. The presence of this documentation indeed led me to believe that the artifacts don't contain a ProGuard file. I'm glad this is not the case.
