### ISSUE TITLE
Adjust 4.1.4 is not uploaded to maven central

### ISSUE THREAD

**Issue by plastiv** [adjust/android_sdk#151]
It is missing. Latest version is 4.1.3 there
https://search.maven.org/#search%7Cga%7C1%7Cadjust

**Comment by nzakharchenko** [comment]
+1

**Comment by nonelse** [comment]
It was not pushed because the only thing that [v4.1.4](https://github.com/adjust/android_sdk/releases/tag/v4.1.4) adds is the Trademob plugin.
Since the core of the sdk was not updated, the code one the maven central would be the same if it was pushed.
We are doing an update soon, so a new version will be there soon

**Comment by plastiv** [comment]
Thx for the quick reply!
