### ISSUE TITLE
Distribute plugins separately from adjust core?

### ISSUE THREAD

**Issue by hidroh** [adjust/android_sdk#154]
Hi,

We were about to upgrade our adjust dependency until I realized that there have been a few plugins added since my last update. They are cool and all but we don't have immediate need for them at the moment.

I'm not sure if there will be a plan for this, but it would be great if plugins can be modularized and distributed separately from the core library, which I'm sure is a must for everyone (the same way Google Play Services were splitted).

It makes us feel safer when we update and know for sure the impact will be limited to only core module (i.e. no extra plugins which may break our app). I believe it will also be beneficial going forward, when the library grows with more plugins added.

**Comment by nonelse** [comment]
Hi and thanks for the feedback.

We have plugins for some partners such as criteo, trademob and sociomantic that can be added to the core adjust SDK.
So far the only way to integrate them was to download the source and manually copy the plugin files into the project.
To facilitate the process, we decided to make new artifact-id in the maven repository for this plugins. They are `adjust-android-criteo`, `adjust-android-trademob` and `adjust-android-sociomantic`, all of them at version `4.1.5`.
The adjust sdk core remains `adjust-android` and it still does not add unnecessary dependencies. 
The current version of the core adjust sdk is still at `4.1.3`, because that is the last time it was updated. Versions `4.1.4` and `4.1.5` only updated plugins.

Cheers.

**Comment by hidroh** [comment]
What about classes under https://github.com/adjust/android_sdk/tree/master/Adjust/plugin? These are actually what I ask to be separated. I know there are just a handful of them now but I'm afraid they may grow a lot more in future updates.

**Comment by nonelse** [comment]
those classes are not part of the source code of the adjust sdk that resides here: https://github.com/adjust/android_sdk/tree/master/Adjust/adjust/src/main/java/

Those plugin classes are to be either copied to the source, or compiled together with a different artifact-id with a different pom file. You can see the instruction of one of the plugins [here](https://github.com/adjust/android_sdk/blob/master/doc/criteo_plugin.md) to see how it can be integrated.

**Comment by hidroh** [comment]
Oh okay I should have RTFM. Thanks! I'll close this.
