### ISSUE TITLE
Android Advertising ID in place of UUIDs

### ISSUE THREAD

**Issue by georgiev-martin** [adjust/android_sdk#159]
If Google Services are available, the Android Advertising ID should be used in place of any UUIDs. The user has control over the the Advertising ID, but not over other types of ids.

https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/Util.java#L63

**Comment by nonelse** [comment]
Hi and thanks for the feedback. 
According to the [Google Play Developer Program Policy](https://support.google.com/googleplay/android-developer/answer/6048248?hl=en), apps cannot use other device identifiers if the Advertising ID is available.
The randomly generated UUID is not part of the device id's and cannot be used to identify the device. It is saved in the activity state and can be deleted by cleaning the data of the app.
We do use other device identifiers besides the Advertising ID if the Google Play Services library is not available. This occurs if the app is not distributed through the Google Play Store.
Hope this cleared your question.

**Comment by georgiev-martin** [comment]
Thanks for the reply!

One of the purposes of the advertising ID is to track the user between sessions. The UUID is used for that same purpose here, too. From that perspective, if the advertising ID is available (Google Play Services is available), it should be preferred over other identifiers (e.g., UUID). 

It is true, that the user can reset the UUID by clearing the app's data, but that would also purge all other data of the app which is far from optimal. In contrast, resetting the advertising ID is straightforward and does not have a collateral damage.

**Comment by sighmoan** [comment]
The primary concern of the advertising ID, though, is to track users between apps, allowing publishers and advertisers to sync on which users have travelled between the two. You can see this more clearly on iOS, where multiple different identifiers have different purposes - IDFA for cross-app, IDFV for internal purposes, etc.

The randomly generated ID here is not a device ID, as it is unique per app, per user, and per installation. You can regard it more as an SDK instance identifier. So that's in line with the guidelines, at least. The privacy recommendations we follow typically regulate sharing data between different actors, but analytics within one and the same provider need a slightly different play. The UUID is adapted to the latter.

So as the other device IDs can vary depending on context, there's a need for a random UUID that's consistent in shape and format across multiple contexts, and that can be used in places where the other IDs are not reliable (e.g. Android IDs are in certain markets not quite reliable.)
