### ISSUE TITLE
ZipException: duplicate entry: com/adjust/sdk/ActivityHandler$1.class

### ISSUE THREAD

**Issue by sergiiz** [adjust/android_sdk#172]
Weird exception when I'm trying to build our big multidex project with the latest Adjust sdk:

```
Error:Execution failed for task ':app:packageAllMasterDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/adjust/sdk/ActivityHandler$1.class
```

Everything builds fine on com.adjust.sdk:adjust-android:4.1.0 but not on 4.2.+ (tried 4.2.2 and 4.2.3).
Also everything builds fine on 4.2.3 if minSdkVersion=21, but not for minSdkVersion=14.

Can't reproduce on small/example projects.

**Comment by uerceg** [comment]
Hi @sergiiz 

I wasn't able to reproduce this thing issue at all.

How are you adding our SDK to your app? Can you show me your `build.gradle` file? Dummy question, but did you maybe double added dependency to our SDK somehow (maybe by adding `compile project(":adjust")` to your `build.gradle` + maybe having our .jar in `libs` folder and including that folder as well into `build.gradle`?

**Comment by hasanizer** [comment]
I've got the same result when adding criteo also.
 ```
compile 'com.adjust.sdk:adjust-android:4.2.3'
 compile ('com.adjust.sdk:adjust-android-criteo:4.2.3'){
        exclude module: 'adjust-android'
   }
```

**Comment by uerceg** [comment]
@hasanizer Can you reproduce this error every time you try to build your project?

**Comment by hasanizer** [comment]
Yes

**Comment by uerceg** [comment]
@hasanizer If you want to use our SDK with Criteo plugin capabilities, all you need to add to your gradle file is:
```
compile 'com.adjust.sdk:adjust-android-criteo:4.2.3'
```

It contains our SDK + Criteo capabilities.

**Comment by hasanizer** [comment]
Ouw, sorry. I'm so stupid. Thanks...

**Comment by uerceg** [comment]
No problemo, glad it worked. :+1: 

@sergiiz Any update on this issue in your case?

**Comment by sergiiz** [comment]
@uerceg thanks a lot! 

Can't confirm right now, I'm on anther subproject. I think my problem was the same so I'm closing the issue.

**Comment by uerceg** [comment]
:+1: Thanks for an update.

**Comment by mustafaberkaymutlu** [comment]
Hi @uerceg 

I am facing the same problem when I try to add both Criteo and Sociamantic plugins.

This doesn't work:
    compile 'com.adjust.sdk:adjust-android:4.11.1'
    compile 'com.adjust.sdk:adjust-android-criteo:4.11.1'
    compile 'com.adjust.sdk:adjust-android-sociomantic:4.11.1'

This also doesn't work:
    compile 'com.adjust.sdk:adjust-android-criteo:4.11.1' // Adjust + Criteo
    compile 'com.adjust.sdk:adjust-android-sociomantic:4.11.1' // Adjust + Sociomantic

> Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForProductionRelease'.
> Job failed, see logs for details

Progard rules are exactly the same with the [docs](https://github.com/adjust/android_sdk#sdk-proguard)

**Comment by uerceg** [comment]
Hi @mustafaberkaymutlu 

You should not add both those lines into your gradle file since our SDK version for specific plugins contain original SDK as well which you are already importing with the first line you wrote in your example. Thus the duplications.

Our packages `adjust-android-criteo`, `adjust-android-sociomantic` and `adjust-android-trademob` are simply our original SDK extend with functionalities for that specific plugin. At the moment we still don't have version that includes all of the plugins, which is the thing that would suit you the best, I would say.

For the time being, you can do following:
- Pick one of the `adjust-android-*` packages to add to your gradle file and for the missing plugin, simply take Java source files from here https://github.com/adjust/android_sdk/tree/master/Adjust/plugin and add them manually to your app and use.
- Pick only `adjust-android-4.11.1` to add to your gradle file and again from this URL https://github.com/adjust/android_sdk/tree/master/Adjust/plugin pick all the Java source files from plugins of your interest and add them to your app in order to use them.

Lemme know if it worked.

Cheers

**Comment by mustafaberkaymutlu** [comment]
Hi @uerceg

Thanks for your quick response!
As you said I ended up importing the source files of Criteo and Sociomantic into my project. I added them together as a separate Android module.

Thanks
Best regards
