### ISSUE TITLE
Device ID not sent when google play services is available.

### ISSUE THREAD

**Issue by sorinirimies** [adjust/android_sdk#189]
I am using google play services but I want to receive the the device ID over the adjust sdk. However this is not possible hence there is a flag in the method inside the DeviceInfo class:

  private String getAndroidId(Context context, boolean isGooglePlayServicesAvailable) {
        if (!isGooglePlayServicesAvailable) {
            return Reflection.getAndroidId(context);
        } else {
            return null;
        }
    }

Would be really great if you can expose this method so that the user of the library can decide if he wants the device ID to be sent, no matter if the project has google play services or not.

**Comment by nonelse** [comment]
Since 2014/08/01, apps distributed through the Google Play Store have the requirement to use advertising ID as the device id: https://support.google.com/googleplay/android-developer/answer/6048248?hl=en 

The reason that we still have a fallback to Android id and hashed mac address is to support non-Google Play Store apps, that usually are distributed in devices that don't have Google Play Services installed.

Does your use case fall outside of this two possibilities?

**Comment by sorinirimies** [comment]
Yes, it falls outside both. We are using google play services, and part of our analytics relies on the device ID sent through Adjust SDK. But interestingly enough, the device ID not being sent only started to happen after we updated the play services to 8.4.0. Is there a possibility to extend the SDK and leave the send device ID decision to the implementer?
Thx.

**Comment by nonelse** [comment]
So your app is not being distributed through Google Play Store and you have installed Google Play Services and still want the SDK to read and send the Android ID, is this right?

If this is something that you want and since you know where the issue is, you can change the source code on your integration to make the SDK read and send the Android ID at your own risk.
 
To have the SDK officially do this as an option is something that we need to consider and maybe have more details on the use case, since it's not a common one.

**Comment by sorinirimies** [comment]
The app is distributed through the play store, we have installed play services and we want the SDK to read and send the Android ID.Reason is a historic one. The initial internal data science guys have implemented the analytics also based on the adjust SDK received device ID. 
I already, downloaded the source code and modified the getAndroidID method. But it is not the cleanest solution, hence every new version update will be handled manually.

**Comment by nonelse** [comment]
We had the same issue during the migration, so we kept sending both values for a while. After enough time, we had the mapping of Andoid Id to Advertising Id, so we were able to drop reading the Android Id to be compliant with Google. 
I suggest for you to do the same thing temporarily, to be able to rely on Advertising Id as soon as possible.
If you really want to continue to have this behaviour, the best way would be to have a fork from our repository with a single commit with this change. It would be only necessary to fetch/rebase to update to a new version.
For now I don't think we want to change the SDK to enable something that could get apps rejected in the Play Store.
