### ISSUE TITLE
Attribution ChangeListener

### ISSUE THREAD

**Issue by jbrick** [adjust/android_sdk#192]
The readme in the faq states:

"If you want to trigger an event after the install, use the attribution changed listener."

Does this mean the attribution changed listener will only be called once per install? Or is additional logic required to enforce that?

**Comment by uerceg** [comment]
Hi @jbrick 

Attribution changed listener is the method which gets triggered when ever attribution changes. By changes, we also consider "first time obtained" as well. 

Once app is installed and opened for the first time, our SDK doesn't know anything about this particular install's attribution. So in first session package we ask backend about it and once we get the answer, we trigger this callback. This callback will get triggered later every time when attribution changes (reattribution). So, you should make sure that your event is tracked only once if you put your logic in there, since the callback itself can be triggered as well at some later point due to reattribution.

**Comment by maltzj** [comment]
@uerceg does this mean that this callback will only be fired when the application is launched?

**Comment by uerceg** [comment]
Yes. I mean, it shouldn't happen that this callback gets triggered after your user was already using the app in foreground for some time. If certain install gets reattributed, this will be figured out upon app launch once new session is being started.

**Comment by uerceg** [comment]
Hi @maltzj 

Do you need any further assistance on this issue?

Cheers

**Comment by Obaied** [comment]
Closed due to inactivity.
