### ISSUE TITLE
Session check interval failed

### ISSUE THREAD

**Issue by apo1981** [adjust/android_sdk#231]
Hi

Let me expose the scenario in my Android app:
1. Install the app and launched
2. App retrieves Adjust Tracker name and Adjust Tracker Token via the onFinishedTracking callback
3. Close, kill and uninstall the app
4. Install again the app and launched
5. onFinishedTracking callback is triggered but with the following error: Adjust Error: Session request check interval failed (Ignoring too frequent session. Last session: 2016-09-19T20:35:17, this session: 2016-09-19T20:39:47, interval: 4m30s, min interval: 20m). So, the app is not able to retrieve Adjust Tracker name and Adjust Tracker Token

Why do I have to wait 20 minutes for reinstall again the app to get these parameters?

Thank and regards,
Antonio

**Comment by uerceg** [comment]
You are missing one step in this flow - forgetting your test device from our backend.

Check this section: https://github.com/adjust/android_sdk#ts-session-failed

**Comment by apo1981** [comment]
is this sth that happen in sandbox or also in production mode?

**Comment by uerceg** [comment]
Тhis error we are describing in the README is implying that you are testing your app in sandbox. Often, users want to emulate "installation and first opening of the app" scenario and see how things look like in that moment (among other things, they also wanna see attribution callback getting triggered, like you in this case).

If you just uninstall the app and reinstall it, our SDK will try to send new session, but if it gets sent within 20 minutes interval, backend will reject it because backend knows about the device and that last session we saw from that device arrived less than 20 minutes ago.

If you delete the device from the backend and when SDK sends session, that time (even if it happens within 20 minutes), session will not be rejected and will be treated as an install. Attribution callback will also get triggered at that moment, because after an install, our SDK will get info about the origin of that install.

**Comment by apo1981** [comment]
Thank you

**Comment by apo1981** [comment]
Hi again, but I checked it using **production mode** and I get the same failure message :(.

If I understood you, this should only happen in sandbox mode right?

**Comment by apo1981** [comment]
any feedback?

**Comment by uerceg** [comment]
Hi @apo1981 

This is not sandbox feature mode only. It behaves the same regardless of the environment you are using it in (sandbox or production). Distinction between environment variables just points the traffic you make to the proper part in your dashboard, but backend behaviour is the same in both cases.

It is the same for iOS platform as well, correct.

Cheers

**Comment by falconxunit** [comment]
Thanks

**Comment by apo1981** [comment]
Hi again,

We would like to know if we have a strange behaviour in our iOS app integrating the SDK because we are using the following method from the delegate to retrieve the tracker name and tracker token once the installation is done and app is firstly run:

(void)adjustAttributionChanged:(ADJAttribution *)attribution

Using this method, iOS app does not return any session failed error as we have discussed during this chat even though the app is reinstall before 20 minutes.

**Comment by uerceg** [comment]
Hi,

That callback is not the one which will deliver you the message that session failed. That one is used to obtain info about the attribution once it changes.

The callback you are looking for is the one which gets triggered when session fails (because install is nothing else than the first session ever and error due to too frequent session will cause it to fail).

The callback you are looking for is:

```objc
- (void)adjustSessionTrackingFailed:(ADJSessionFailure *)sessionFailureResponseData {}
```

You can read more in this section: https://github.com/adjust/ios_sdk/#event-session-callbacks

**Comment by apo1981** [comment]
I see your point, but why the adjustAttributionChanged method is triggered is such a case?

**Comment by uerceg** [comment]
If there's a standard first install and launch scenario happening, install will be tracked and `adjustAttributionChanged` will be triggered.

If you uninstall the app and reinstall it and launch it in the time interval less than 20 minutes, you will get the info that session tracking failed due to too frequent session request and this info will be delivered in `adjustSessionTrackingFailed` callback.

In that moment, `adjustAttributionChanged` will not be triggered automatically, but rather upon next session or subsession (you can just put your app to background and return it to foreground and you will see `adjustAttributionChanged` getting triggered.

And why?

Well, by deleting your app, you have deleted our SDK as well and all info it kept. With each new install, our SDK has no information about attribution and thus, it will ask about it. Once it asks and gets info about it, it will trigger the `adjustAttributionChanged` in cases where it got it **for the first time** or **when it changed it's value from what SDK currently has as attribution value**.

**Comment by uerceg** [comment]
@apo1981 What's the status on this one?

**Comment by Obaied** [comment]
Closed due to inactivity, please feel free to reopen the issue if it still persists with latest SDK version.

**Comment by shinriyo** [comment]
What is this error?

**Comment by shinriyo** [comment]
I'm seeing the "Session failed (Ignoring too frequent session. ...)" error.
This error typically occurs when testing installs. Uninstalling and reinstalling the app is not enough to trigger a new install. The servers will determine that the SDK has lost its locally aggregated session data and ignore the erroneous message, given the information available on the servers about the device.

This behavior can be cumbersome during testing, but is necessary in order to have the sandbox behavior match production as much as possible.

You can reset your app's session data for any device directly from the Adjust Dashboard using our Testing Console if you have Editor-level access (or higher) to the app.

Once the device has been correctly forgotten, the Testing Console will return Forgot device. If the device was already forgotten (or if the values were incorrect) the link will return Advertising ID not found.

Forgetting the device will not reverse the GDPR forget call.

If your current package gives you access, you can also inspect and forget a device using our Developer API.

**Comment by shinriyo** [comment]
Do fail safe

**Comment by ugi** [comment]
Hi @shinriyo,

What exactly do you suggest?
