### ISSUE TITLE
Install Event not tracked on Dashboard

### ISSUE THREAD

**Issue by apo1981** [adjust/android_sdk#234]
Hi

We are testing our app using sandbox enviroment, installing the app from Android Studio IDE and unistalling it, it seems that the logs are ok because we are able to retrieve the tracker name and tracker token, but we are not able to observe the install event on the app adjust dashboard, however the session seems to be updated.

Adjust SDK: compile 'com.adjust.sdk:adjust-android:4.10.2'

Finally let me show you the log (Adjust Id: {AppToken}):

10-27 15:28:46.675 5639-5639 A/Adjust: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!
10-27 15:28:46.708 5639-6649 D/Adjust: Attribution file not found
10-27 15:28:46.717 5639-6649 D/Adjust: Activity state file not found
10-27 15:28:46.745 5639-6649 D/Adjust: Session Callback parameters file not found
10-27 15:28:46.746 5639-6649 D/Adjust: Session Partner parameters file not found
10-27 15:28:48.926 5639-6649 I/Adjust: Google Play Services Advertising ID read correctly at start time
10-27 15:28:48.928 5639-6649 I/Adjust: Send in background configured
10-27 15:28:48.974 5639-6748 D/Adjust: Package queue file not found
10-27 15:28:49.339 5639-6649 D/Adjust: Wrote Activity state: ec:0 sc:1 ssc:1 sl:0.0 ts:0.0 la:11:12:13 uuid:ad2b003e-267a-45ca-9e6e-6b4729100011
10-27 15:28:49.340 5639-6757 D/Adjust: Added package 1 (session)
10-27 15:28:49.343 5639-6649 D/Adjust: Wrote Activity state: ec:0 sc:1 ssc:1 sl:0.1 ts:0.1 la:11:12:13 uuid:ad2b003e-267a-45ca-9e6e-6b4729100011
10-27 15:28:49.345 5639-6649 D/Adjust: Wrote Activity state: ec:0 sc:1 ssc:1 sl:0.1 ts:0.1 la:11:12:13 uuid:ad2b003e-267a-45ca-9e6e-6b4729100011
10-27 15:28:49.376 5639-6757 D/Adjust: Wrote Package queue: [session]
10-27 15:28:49.376 5639-6757 D/Adjust: Package handler wrote 1 packages
10-27 15:28:49.732 5639-6759 I/Adjust: Session tracked
10-27 15:28:49.753 5639-6766 D/Adjust: Wrote Package queue: []
10-27 15:28:49.754 5639-6766 D/Adjust: Package handler wrote 0 packages
10-27 15:28:49.768 5639-6767 D/Adjust: Wrote Activity state: ec:0 sc:1 ssc:1 sl:0.1 ts:0.1 la:11:12:13 uuid:ad2b003e-267a-45ca-9e6e-6b4729100011
10-27 15:28:49.778 5639-6649 D/Adjust: Wrote Attribution: tt:2k44xm tn:Organic net:Organic cam:null adg:null cre:null cl:null
10-27 15:28:49.782 5639-6649 D/Adjust: Launching success session tracking listener

According to this link: https://github.com/adjust/android_sdk, we should see an Install tracked log, but we dont see it

Any light on it?

**Comment by uerceg** [comment]
Hi @apo1981 

Couple of things.

1. I guess you have either set adjust log level to be `debug` or your LogCat filter is showing only `debug` and higher log level. Make sure to change both to `verbose` so that you can see more informative log output.
2. Uninstalling the app and simply re-installing it afterwards will not cause install to happen, because once install happened from your device, our backend knows about it and will not treat any new session as install unless you explicitly forget your test device from our backend. How to do that is described in this chapter (although this chapter describes one potential testing issue, the forgetting device procedure is always the same and you should perform it): https://github.com/adjust/android_sdk#ts-session-failed. After you uninstall the app from your device, **forget the device from our backend** and then reinstall and re-run the app on the device, you will see that install is being tracked.

Give it a try and lemme know if you need any further assistance with this.

Cheers

**Comment by apo1981** [comment]
Thks @uerceg for your feedback.

Following your steps, I can see now the Install tracked in the log and the following message: Adjust] onFinishedSessionTrackingSucceeded: Session Success msg:Install tracked time:2016-10-27T13:54:46.497Z+0000 adid:754a817aec7b4625f53c5e02c1b14caf json:{"app_token":"hz6rtwb96ker","adid":"754a817aec7b4625f53c5e02c1b14caf","timestamp":"2016-10-27T13:54:46.497Z+0000","message":"Install tracked","attribution":{"tracker_token":"2k44xm","tracker_name":"Organic","network":"Organic"},"ask_in":2000}

But, I am not able to see the install event on the dashboard yet :(. Is there a delay to update the events on the dashboard?

**Comment by uerceg** [comment]
Good news! 👍 

Yep, there should be a bit of delay between the moment when install is tracked and when that info is displayed in the dashboard.

To get info about exact time of this delay, please contact your dedicated AM or simply send email to our support which can provide you with an answer to this question on support@adjust.com

**Comment by apo1981** [comment]
But, how can I be sure that pointing to Production is going to work? Logs are disabled :(

**Comment by uerceg** [comment]
Well, if it works in sandbox, with just changing production environment before releasing the app to production, it must work. :)

You can repeat the same procedure with environment variable set to production and after a bit, check the dashboard and you'll see install count being increased for the installs in production.

**Comment by apo1981** [comment]
Thks so much for your support @uerceg 

Just to summary and completely understand how the platform works in terms of how the install and session events are recorded (and showed on the dashboard), let me show you some scenarios where I described my understanding:

**- Scenario 1:**
Device not registered in Adjust platform,
App not installed on the device,
App is installed on the device,
App is opened
Device is registered in Adjust platform,
Install event is recorded
Session event is also recorded

**- Scenario 2:** 
Device already registered in Adjust platform,
App installed on the device
App is uninstalled
App is installed on the device before 20 minutes session expiration
App is opened
Install event is not recorded
Session event is not recorded

**- Scenario 3**
Device already registered in Adjust platform,
App installed on the device
App is uninstalled
App is installed on the device after 20 minutes session expiration
App is opened
Install event is not recorded
Session event is recorded

**- Scenario 4**
Device already registered in Adjust platform,
App installed on the device,
App is uninstalled,
Forget device from Adjust platform,
App installed on the device
App is opened
Install event is recorded
Session event is recorded

**- Scenario 5**
Device already registered in Adjust platform,
App is updated with a new version
App is opened
Install event is not recorded
Session event is recorded

Please, let me know if this is the expected behaviour

**Comment by uerceg** [comment]
Yes, you understood it well. Only few minor corrections:

**- Scenario 2**
Session time is 30 minutes, not 20 (if you made this conclusion based on error message you are getting from the backend in session too frequent scenario, that's because backend considers 20 minutes as timeframe for the next session, but SDK is keeping it at 30 minutes).

**- Scenario 3**
Same as above, session is 30, not 20 minutes.

**- Scenario 5**
True if update has been done and app launched afterwards outside of 30 minutes session frame.

**Comment by apo1981** [comment]
Again, thks so much
