### ISSUE TITLE
Bug in the example for setting Google Analytics cid parameter

### ISSUE THREAD

**Issue by stufan** [adjust/android_sdk#249]
According to https://docs.adjust.com/en/special-partners/google-analytics/#adjust-sdk-and-google-analytics-sdk to override Google Analytics cid parameter to be equal to the one from Adjust the example states the following code:

  mTracker = analytics.newTracker(R.xml.global_tracker);
  Adjust.getGoogleAdId(this, new OnDeviceIdsRead() {
      @Override
      public void onGoogleAdIdRead(String googleAdId) {
          mTracker.set("&cid", googleAdId);
      }
  }

However OnDeviceIdRead() callback is invoked as AsyncTask which basically means that the entire Adjust.getGoogleAdId() completes slightly earlier than mTracker.set("&cid", googleAdId); line is executed which may result in incorrect setting of GA SDK client_id.

**Comment by uerceg** [comment]
Hi @stufan 

And thanks for reporting this.

Google Play Services Advertising Identifier can not be accessed from the main thread, but it rather needs to be performed in the background. That's the reason why we're having this callback mechanism for obtaining it's value.

You say: `which basically means that the entire Adjust.getGoogleAdId() completes slightly earlier than mTracker.set("&cid", googleAdId);`

Since we're no GA SDK experts, can you explain us why earlier finishing of the `Adjust.getGoogleAdId()` results in incorrect setting of GA SDK? Shouldn't it be finished before setting the GA tracker? Also, do you maybe have some suggestion in how this integration should be done so that it works as expected?

Looking forward to hear from you.

Cheers

**Comment by uerceg** [comment]
Hi @stufan

Any update on this?

Cheers

**Comment by stufan** [comment]
As GA SDK is not open sourced my suggestion is to make the call for Google Ad Id on the main thread as it is pretty fast and won't block the execution of the app. At the same time it will simplify the usage of Adjust SDK.

**Comment by uerceg** [comment]
It is not possible to get Google Play Advertising Id on the main thread.

Reference: https://developers.google.com/android/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient#getAdvertisingIdInfo(android.content.Context)

```
This method cannot be called in the main thread as it may block leading to ANRs.
An IllegalStateException will be thrown if this is called on the main thread.
```

This is why it must be done asynchronously and be accessed in the way like it is implemented in the SDK.

Would be nicer if it could be accessed in the main thread and if the value could be obtained directly, but unfortunately, that's not the case.

**Comment by uerceg** [comment]
Hi  @stufan 

Is it okay to close this issue?

Cheers

**Comment by stufan** [comment]
I think so

Thanks
