### ISSUE TITLE
Could Not Find The Impressions on ReadMe

### ISSUE THREAD

**Issue by egemenhamutcu** [adjust/android_sdk#272]
How can I implement every page view reporting to Adjust? You have Impressions in your docs, right? [https://docs.adjust.com/en/impression-tracking/](https://docs.adjust.com/en/impression-tracking/)

**Comment by uerceg** [comment]
Hi @egemenhamutcu 

Impression tracking feature is something that (function wise) has nothing to do with SDK, thus it's not written in README. That feature is something you can enable in your dashboard to see if some of your users are getting attributed to impressions and not only clicks. For that, you need to use different URLs for your impression(s) source(s) and the whole logic behind this feature is behind the scenes on our backend.

SDK operates normally and sends sessions/events and backend decides later if something should be attributed to the impression (if it happened) and if yes, that will be displayed in the dashboard.

Our README is containing only SDK related things and if going outside of that scope, only thing which, in order to work properly, something needs to be set in the SDK itself. If SDK has nothing to do with the feature from our official docs, we just don't write those things in here.

Cheers

**Comment by dpoetzsch** [comment]
I'm not sure but I think there is some confusion going on here.

One thing is page view tracking. For example we'd like to track every Activity the user opened to get a feeling of the user flows. We want to forward this data to google analytics as page views (not events!). Is something like this possible?

Impression tracking is something very different, right? As far as I get it impression tracking is about connecting a view of an ad with an install or conversion.

Could you clear this up please?

**Comment by egemenhamutcu** [comment]
Our team have decided to use event tracking for page views.

**Comment by uerceg** [comment]
From what I see by reading these screen hits docs, for me it seems something that I would do like @egemenhamutcu suggested - simply creating event for that purpose and track it once screen gets opened.

Is there some reason why this approach wouldn't work for you maybe @dpoetzsch ?

**Comment by egemenhamutcu** [comment]
It would be better to advance ReadMe for those who is having the same confusion with me

**Comment by dpoetzsch** [comment]
@uerceg Actually this is what we tried so far. We track an event and set the `cd` partner parameter to the activity name. The `ActivityLifecycleCallbacks` come in very handy for that.

However, we are stuck when it comes to properly forwarding the event data to google analytics. We can forward it as an event, no problem. But from what I understand google treats events and screen hits differently. What I don't see is: How can I tune adjust to forward an event to google analytics as a screen hit? (so we can see them in the analytics console under screens, not under events)

**Comment by uerceg** [comment]
@dpoetzsch 

Sorry for a delay on this one.

This is actually kinda out of our scope and actually a thing that you should ask our account management team. In case you have a dedicated account manager, feel free to approach with this question or if not, feel free to ask this in email which you can send to support@adjust.com.

Also feel free to write in there any suggestion you are having when it comes to docs improvement.

**Comment by uerceg** [comment]
Feel free to reopen the issue in case you have any issues, but like advised, when it comes to this topic, support@adjust.com is definitely better place to ask for help. Cheers.
