### ISSUE TITLE
Building the app with basic sdk integration doesn't show Install tracked in the logs

### ISSUE THREAD

**Issue by lawloretienne** [adjust/android_sdk#294]
So i should be seeing `Install tracked` in the LogCat
https://github.com/adjust/android_sdk#build-your-app

instead it logs the following

```
W/Adjust: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!
D/Adjust: Attribution file not found
D/Adjust: Activity state file not found
D/Adjust: Session Callback parameters file not found
D/Adjust: Session Partner parameters file not found
D/Adjust: adjust_config.properties file not found in this app
I/Adjust: Google Play Services Advertising ID read correctly at start time
D/Adjust: Package queue file not found
```

Are there some more things that need to be configured in the dashboard?

**Comment by uerceg** [comment]
@lawloretienne 

To have better overview on what's happening inside of the SDK (all the logs), when testing maybe try to set log level to `verbose` to get as much as info as possible from the SDK (https://github.com/adjust/android_sdk#adjust-logging).

Did you pay attention to this chapter of the README: https://github.com/adjust/android_sdk#session-tracking ?

This is important, since `Adjust.onCreate` method will initialise SDK with configuration it needs (that's where you're passing `AdjustConfig` object to), but `Adjust.onResume()` call will actually start the tracking of things.

**Comment by lawloretienne** [comment]
Thanks so much for the speedy response.  I was calling `registerActivityLifecycleCallbacks()` in an if block but not calling it in an else block.  So the `Adjust.onResume()` never got called.  I fixed that so its working now.  I can see the `Install tracked` and `Attribution found` in the LogCat.
