### ISSUE TITLE
Is it possible to initiate Adjust session out of Application class?

### ISSUE THREAD

**Issue by apo1981** [adjust/android_sdk#299]
Hi,
Following your step-by-step integration guidelines, it is indicated that the Adjust.onCreate(AdjustConfig) must be called on our Application class.

This is fine and perfectly works, but I am wondering if it is possible to call - and make work - this method (Adjust.onCreate(AdjustConfig)) out of the Application class. The reason behind that is because we would like to fetch Adjust configuration included the Adjust app token from a external network service.

Thks in advance

**Comment by uerceg** [comment]
Hi @apo1981

Sure, you can do that. We do not advise it in general, but in theory it is doable. One thing you need to have in mind is that Adjust.onResume() call actually starts the SDK. So if you maybe do the initialisation (onCreate) in middle of Activity, SDK won’t start until onResume gets called (probably on first transition between activities in your app). So maybe just in case make a call to Adjust.onResume() after onCreate in this use case.

**Comment by apo1981** [comment]
Thks @uerceg . I was missing to add Adjust.onResume(). I am forcing after onCreate, and it works

**Comment by Obaied** [comment]
@apo1981 
Feel free to close the issue if it has been solved :)

**Comment by uerceg** [comment]
👍 

Glad it works, but be careful when it comes to this kind of usage. It can affect some other functionalities of the SDK. For example, if you want to enable reattributions through deep linking, you'll need to follow this part of the guide: https://github.com/adjust/android_sdk#deeplinking. In there, you can notice that scheme that opens your app gets delivered to certain activity's `onCreate` or `onNewIntent` methods and we expect you to call `Adjust.appWillOpenUrl` method so that we handle things and do potential reattribution on backend side. But, call to `appWillOpenUrl` method is useless if SDK is not initialised. And if we assume that your activity where this info arrives is the one where you initialise your SDK, it might happen that you maybe make this call before SDK gets initialised and this feature won't really work for you due to your particular use case.

This was just an example. Bottom line with this approach you took is - yes, it is possible and yet, things can work, but you need to be careful and make sure that all the things you're expecting from SDK to do actually work well, so make sure that you double check them all and test things properly.

In case you have some other questions, feel free to ping us in here.

Cheers. 🍺
