### ISSUE TITLE
Does deferred links only works on first time ever install?

### ISSUE THREAD

**Issue by belalfyndiq** [adjust/android_sdk#310]
If the User uninstalled the App and Later on clicked on a link from adjust Deferred links does not work.
Is this the Expected behaviour from deferred links?

**Comment by uerceg** [comment]
Hi @belalfyndiq 

There are several things to have in mind when testing this use case (getting deferred deep link after reinstalling an app).

First thing to have in mind is that tracker URL you are clicking onto needs to contain different tracker (user needs to be reattributed from original tracker to which install was tied to). Just altering `deep_link` parameter content will not work if you have same tracker token in the URL.

Won't work:

```
1st link: https://app.adjust.com/abc123?deep_link=appscheme%3a%2f%2fmy-deeplink-content-1
2nd link: https://app.adjust.com/abc123?deep_link=appscheme%3a%2f%2fmy-deeplink-content-2
```

Will work: 

```
1st link: https://app.adjust.com/abc123?deep_link=appscheme%3a%2f%2fmy-deeplink-content-1
2nd link: https://app.adjust.com/def456?deep_link=appscheme%3a%2f%2fmy-deeplink-content-2
```

Next thing to have in mind is that reinstall needs to happen within next session time. For Adjust, interval between sessions is 30 minutes. So if last session for your app was tracked at 12:00:00, you need to reinstall your app (after which SDK will by default fire session request to our backend) at 12:30:00++, because reattribution in this case can happen only within new session.

And also, final thing to have in mind is `Inactivity period` setting under `Attribution -> Reattribution` settings in the dashboard. Next to the fact that reinstall session needs to happen after 30+ minutes since last session from your device was tracked, it also needs to happen outside of that time interval so that click you make on URL 2 would be considered for reattribution by our backend.

Hope this helps you. Let us know if we can help you with anything else.

Cheers

**Comment by belalfyndiq** [comment]
Thanks A lot this is more than clear.

**Comment by uerceg** [comment]
👍 Do you have any further questions or can this issue be closed?

**Comment by belalfyndiq** [comment]
all good I will close the issue 👍
