### ISSUE TITLE
Adjust.setEnabled() has a delay of about 150ms when checking with Adjust.isEnabled()

### ISSUE THREAD

**Issue by kihaki** [adjust/android_sdk#335]
1) Disable Adjust in the Application's onCreate with Adjust.setEnabled(false)
2) Check if Adjust is enabled in the first Activity (MainActivity) with Adjust.isEnabled()

The test will return true, even though Adjust should be disabled.
When rerunning the test every 50ms (via postDelayed()) Adjust seems to disable itself about 150ms after the start of the MainActivity.

This caused issues for us where we got false positives of Adjust being still enabled right after disabling it.

This is an important implementation detail and should probably at least be documented.

**Comment by uerceg** [comment]
@kihaki Thanks for sharing the info, sure we can document that, but this is kinda how SDK works. Disabling SDK is not asynchronous action. Tracking of packages and lots of other actions in SDK are checking for disabled/enabled state before being performed. We made it in a way where we assume that if user said that event should be tracked and then disabled SDK afterwards, this event should be queued and added to the package queue to be sent at some point. If disabling was async, it would probably manage to set disabled flag way faster than code path for queueing event gets executed, thus resulting in event being dropped even though `trackEvent` was called before disabling SDK. With that in mind, SDK disabling/enabling is synchronous operation so that we are able to honour everything that might have happened prior to that call.

On the other side, reading of the disabled state will give you info about it at that time. We're considering to maybe make some different logic around this when we jump to mayor version 5.0.0, but currently, this is how it works and sure, it would be no problem for us to document this in the README. In case you have any ideas how you would like to see this topic covered in the SDK from implementation point of view, feel free to share your thoughts with us, would be great to hear client's opinion as well.

Just out of curiosity - can you elaborate a bit on the use case in which you are needed to disable SDK in Application's onCreate method and re-enable it right away in first Activity's onCreate/onResume? Sounds to me like it might be done in different way, but maybe use case is specific, so would just like to know why are you using SDK in this way.

**Comment by uerceg** [comment]
@kihaki Any update on this one?

**Comment by uerceg** [comment]
In case needed, feel free to comment further or reopen the issue.
