### ISSUE TITLE
Incorrect initial attribution data

### ISSUE THREAD

**Issue by kkrol2** [adjust/android_sdk#344]
We have this really weird problem that occurs after we remove attribution data connected to advertising id via adjust's testing console.

Initial state: user is attributed to campaign C. 

1. Clear application data.
2. Forget the device in adjust's console.
3. Launch application from app drawer and wait few seconds.

**Result**
User gets attributed to campaign C and deeplink connected to that campaign is opened.
**Expected result**
User is attributed to organic tracker and no deeplink is opened.

It looks like "forget device" feature is not working correctly.

**Comment by uerceg** [comment]
Hi @kkrol2 

This is feature that should work for sure, we from SDK team are using this on daily basis for testing. I'd advise you to write an email to your dedicated account manager or at support@adjust.com, because support will be able to track your particular test install and also request in which you attempted to forget the device and see where did things go wrong so that you still ended up with same attribution for this install.

**Comment by kkrol2** [comment]
Ok, thank you. I will contact support.

**Comment by uerceg** [comment]
Closing this one, feel free to reopen in case there's need for it.

Cheers
