### ISSUE TITLE
AdID Listener

### ISSUE THREAD

**Issue by xgear-public** [adjust/android_sdk#345]
Hello!
You have following API:
`Adjust.getAdid();`
Could you please add "onAdidReadyListener" to the Adjust API? We use this API but it is hard to catch the moment when it is return non-null and hard to build our custom logic over this API.

**Comment by uerceg** [comment]
Hi @xgear-public 

Nice idea, but in theory there is already API inside of SDK to which you can hook up in order to get this information. `adid` is available to SDK in moment when install is tracked for your user and which is the moment in which (if set), session success callback is triggered: https://github.com/adjust/android_sdk#session-event-callbacks

If you check, `AdjustSessionSuccess` object contains `adid` field (https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/AdjustSessionSuccess.java#L13) and you can access it in that moment, since that is first moment when SDK is setting this field to user's disposal. Also, after this callback is triggered, you should be able to safely call `getAdid()` method and get actual `adid` value.

**Comment by xgear-public** [comment]
Thank you! That would help me!
