### ISSUE TITLE
Is it possible to limit Adjust to install referrer tracking?

### ISSUE THREAD

**Issue by dlew** [adjust/android_sdk#354]
Hello,
We're looking into using the Adjust SDK for the purpose of install referrer tracking, and also for some welcome screen events (such as whether they sign up/log in after being referred to the app).

However, it looks like the SDK is setup to provide full app tracking - wanting a full `ActivityLifecycleCallbacks` implementation that fires every time any `Activity` resumes/pauses. However, for most of the app's usage, we don't want the overhead of running the Adjust SDK - once the user is logged in, we no longer need its services.

I was wondering if it's possible to either:

1. Provide a way to do install referrer tracking and a handful of events without full lifecycle tracking OR
2. Only do lifecycle tracking for the duration of the welcome screen (and then disable it for the rest of the app) without there being any ill side effects.

**Comment by uerceg** [comment]
Hi @dlew 

In theory, yes.

Reason why we want our SDK to be hooked onto `ActivityLifecycleCallbacks` `onResume/onPause` methods is that we need a way to obtain information whether app is in foreground or background. This information is needed for proper session tracking and all bunch of statistics later displayed on the dashboard.

Just to mention, upon `Adjust.onResume()`/`Adjust.onPause()` calls there's no networking involved most of the time (there's networking involved if app was in background for more than 30 minutes and then upon next `Adjust.onResume()`, SDK will send `session` package to our backend). In case you are only worried for SDK doing networking calls when being invoked in other activities of your app, that's probably not gonna be that often case at all.

But in case you simply don't wanna interact with SDK at all, sure, you can skip hooking it up to `ActivityLifecycleCallbacks` methods.

One thing you need to have in mind. When invoking `Adjust.onCreate` method, SDK is getting initialised, doesn't actually start to work. `Adjust.onResume()` is actual call that makes it start and do stuff. So, if you unhook SDK from activity lifecycle methods, it would be good to manually invoke `Adjust.onResume()` method right after you make a call to `Adjust.onCreate`. Also one thing to have in mind in here is that if you do SDK initialisation while your initial activity is still not displayed, SDK will try to send install `session` package upon initial launch and that might be attempted from background. If you do not wish any networking from background, then might be wise that first activity's `onResume()` method actually invokes `Adjust.onResume()`. For example, I'd say "good" way in this use case of yours might be if you initialise SDK (`Adjust.onCreate`) inside of your `Application`'s class `onCreate` method and then invoke `Adjust.onResume()` on your first activity's `onResume()` method.

Just want to make you aware that this is not how SDK usage is intended, but if that suits your needs, feel free to give it a try. Not sure who's on your side looking at data on dashboard for your app, but in this SDK integration, daily active users, session counts and any other metric that might be dependant from proper session counting on SDK side will be skewed and practically useless.

Other hacky way that comes up to my mind is that you can follow SDK integration completely like stated in README, but control SDK with `setEnabled` method. You can disable SDK with `Adjust.setEnabled(false)`. After this call, even though SDK is hooked to all lifecycle methods, it will not do a thing. It's still initialised and remains in memory, but will perform no actions at all unless you explicitly call `Adjust.setEnabled(true)` at some later point. Bare in mind that "enableness" of SDK is something that is persisted between app launches, so if you disable it on one app run and you restart an app (by killing it and wiping it from memory), SDK will still be disabled. So in this flow, you might want to explicitly make a call to `Adjust.setEnabled(true)` as first thing you do with the SDK and then initialise it afterwards. It's also not really advised way of usage, but might work for you.

Feel free to give some of these a shot and let us know if you have any further questions.

Cheers

**Comment by dlew** [comment]
Thanks for the detailed response, I appreciate it.

I've been experimenting with just calling `Adjust.onResume()` once, but I'm still seeing background activity long after I've finished working with Adjust. In particular, in the logs I see "Foreground timer fired" every minute unless I also call `Adjust.onPause()` at some point. Would it be safe to immediately call `Adjust.onPause()` as well, just so that Adjust has a chance to fire its events, but doesn't have an ongoing timer in the background afterwards?

**Comment by uerceg** [comment]
Hi @dlew 

Sorry for a bit delayed answer.

You got it right. Default SDK behaviour is that it won't send anything after call to `Adjust.onPause()` has been made. There is a setting to bypass that behaviour (https://github.com/adjust/android_sdk#background-tracking), but not sure if that's interesting at all for your use case.

`Adjust.setEnabled(false)` should be (depending on SDK version you use, but if latest, it definitely should) synchronous with previous calls you made to our SDK. So in theory, if you say `Adjust.trackEvent(event)` and after that immediately you call `Adjust.setEnabled(false)`, event should still be tracked.

But there is also a convenient way for you maybe to pull out what you're trying. Scenario might somehow look like this: 

- Update SDK to latest version (important, since it contains one feature we added to SDK which might help you). 
- When initialising SDK, implement event tracking success callback (https://github.com/adjust/android_sdk#session-event-callbacks). In here, you will get information that your event has been successfully tracked.
- In case your event is uniquely tracked in your app, event token itself is good enough distinction for you to know that event you have been waiting for to be successfully tracked is indeed the one that got tracked, since event success object which is delivered into callback contains event token info: https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/AdjustEventSuccess.java#L14.
- However, if you are maybe tracking same event multiple times and you are waiting maybe for n-th successful tracking of your event, then with each event tracking, you can define something called callback ID (https://github.com/adjust/android_sdk#callback-id) which is your custom defined string identifier for event that is being tracked and which will later get delivered to you in event success callback (https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/AdjustEventSuccess.java#L15).
- After you attempted to track event and it was tracked successfully, your event tracking success callback method will get pinged and now in here you have a "safer" ground to disable SDK.

Maybe worth giving a shot.

**Comment by dlew** [comment]
That looks like it'll work, thanks.

Is there any danger that the install referrer code will somehow fire *after* the event? I don't think that could be the case, since the install referrer should fire the moment you open the app, but I am not too familiar with that service.

**Comment by uerceg** [comment]
I would say it's hard that it can happen before event you're tracking. Especially if you are using Google install referrer library (which is highly advised that you do). If you are, SDK is pinging it immediately upon initialisation and sends `sdk_click` package with referrer info right away, almost at the same time with install `session` package. So it should definitely reach our backend before your event.

**Comment by uerceg** [comment]
@dlew Will close this one, but in case you still have questions about it, feel free to comment/reopen it. Cheers!
