### ISSUE TITLE
[Question] How can I force check uninstallation on device?

### ISSUE THREAD

**Issue by aleien** [adjust/android_sdk#357]
Hello! We'd like to implement uninstalls tracking, but we wanted to find a way to check if device is being marked as installed/uninstalled respectively. 

We found https://docs.adjust.com/en/adjust-for-developers/#device-api option to inspect device, but will it update info? Or will we need to wait full day before checking?

**Comment by uerceg** [comment]
Hi @aleien 

If you wanna test it to see it in the dashboard and within Adjust ecosystem, then yes, you would need to wait for our backend to process all the apps and update data on the dashboard.

But at the end of the day, this is also something you can in theory test on your own as well, since there's no magic when performing sending of silent push notifications, it's well documented and known flow which you can test as well. The only thing we expect you to perform is to obtain FCM push token for your user and provide this info to our SDK. After you obtain the token, flow says that you should provide it as a parameter of the `setPushToken` method. After that, we simply inform our backend about it which will use it to check once a day if your app is still there on end user's device or not.

You can test this on your own as well by running simple `curl` command:

```
curl -X POST https://fcm.googleapis.com/fcm/send -H 'Authorization: key=your-key-that-you-provided-in-adjust-dashboard' -H 'Content-Type: application/json' -d '{"to": "fcm-token-you-provided-as-parameter-of-setPushToken-method", "content-available":"1"}' -v
```

Once sent when app is installed on your device, you should see reply from Google that everything went well, else, you will see that app is not registered anymore, indicating that it was uninstalled.

If this flow works as expected, then it would most probably work well within Adjust platform as well, but like said, in order to do real test with us, you would need to wait, like you said in your question.

**Comment by aleien** [comment]
That's great! Thank you very much. We'll try this immediately!

**Comment by uerceg** [comment]
Hi @aleien 

Any update on this one?

**Comment by aleien** [comment]
Yeah, we finished all we needed to!
Thank you very much for your help
