### ISSUE TITLE
Bundle R8/proguard config

### ISSUE THREAD

**Issue by plastiv** [adjust/android_sdk#361]
R8 allows to bundle proguard(obfuscation) rules inside of the `.jar`

R8 is going to replace proguard for android users https://android-developers.googleblog.com/2018/11/r8-new-code-shrinker-from-google-is.html

Bundling rules helps with the issue described here: https://github.com/adjust/android_sdk/issues/332#issuecomment-385965764

Related: https://github.com/adjust/android_sdk/issues/147

For example, you can investigate adding rules from square libraries: https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro

**Comment by uerceg** [comment]
Hi @plastiv 

Thanks for advice. We're gonna investigate how can we add R8 support to JAR library.

Will keep you posted on the topic.

**Comment by uerceg** [comment]
@plastiv 

Thanks for the hints in the issue, we did investigation a bit and even though we managed to bundle rules into Android library type of JAR (with a bit of dirty work), we reached the conclusion that it's not worth going that road just for R8 support, especially since R8 is still unofficial + transition from ProGuard to R8 will last for quite a bit.

We'll go with shift to AAR distribution from current JAR approach and bundle things in there to work for all the cases. We added this task into our TODO queue, so from upcoming Android SDK update(s), this should hopefully be live.

Will ping you in here once we went live with it.

Cheers

**Comment by uerceg** [comment]
Update on this one - we are now set to deliver SDK as AAR as of next version, but we just don't have anything to update in a while, thus the delay. Will close this issue to honour initial request for this feature which is waiting for quite a while in the queue (https://github.com/adjust/android_sdk/issues/147). Keep an eye on that one for final notice that SDK was shipped as an AAR with ProGuard rules bundled inside.

Cheers!

**Comment by tinsukE** [comment]
@uerceg quite some releases happened since your last message, all of them as JAR files. Any new ETA for AAR support?
