### ISSUE TITLE
Is it possible for a client to supply their own ThreadPoolExecutor instance?

### ISSUE THREAD

**Issue by brendan-keepsafe** [adjust/android_sdk#365]
This would be a great option to help clients conserve memory and optimize CPU usage.

**Comment by nonelse** [comment]
Hi @brendan-keepsafe, thanks for the suggestion.

Have you tried v4.16.0 or newer? We refactored the executor the sdk uses in it. We benchmarked the system provided `ScheduledThreadPoolExecutor` we were using before and it had issues at high volumes or low powered device.

Besides the api design decision of what to include in the sdk in terms of product usefulness, simplicity and so on, the sdk currently expects the executors to be single threaded for internal synchronization. Changing that would be a major overhaul, and most likely that is not a bottleneck for the sdk. I also think that other changes would be needed in the backend, to make that change worthwhile.

With that current restriction in mind, we would like to know how could the current version could be improved, since that is something we are always looking forward to do.

**Comment by brendan-keepsafe** [comment]
Hi @nonelse, thanks for the reply. My suggestions was more from the perspective of a client developer looking at mostly 3rd party threads when profiling. It seems like we could probably prevent a decent amount of garbage collection and the excessive memory overhead of many threads, if clients could supply a shared executor to all 3rd party libraries.

In our use case, we implement one tracking event with Adjust for a successful purchase. We also have Adjust#onResume and Adjust#onPause hooked up to fire in activity lifecycle callbacks.

I see roughly 4 Adjust threads on app startup (test with 4.16.0 as suggested). One of those threads is active for the first few seconds after a cold launch. The other three threads have 1-2 uses in the first 30 seconds, go to sleep, and eventually die. It would be great if we could have Adjust use just one thread. It would be even better if we could supply our own dedicated analytics executor.

**Comment by nonelse** [comment]
Sorry if we haven't replied earlier, but our current sdk is not setup for such a technical customisation and it's hard to see how we could change it, for a very technical detail that it will increase the complexity of the code and mostly be marginally used.

It is possible that such a customisation, could be tuned not in a public facing API like the `Adjust.java` that is targeted towards business use cases, but in a more internal API that we use for tests.
The suggestion opened up for that overriding possibility in a next major version of the sdk and we will consider others that might made sense to override, but not on the current version as said before. Thanks for it!
