### ISSUE TITLE
Time span since last activity too short

### ISSUE THREAD

**Issue by Amabella** [adjust/android_sdk#383]
Hello, so sometimes when I intend to send event to adjust, it always comes up like this. I don't know what might be causing this things? Could you please tell me how to fix? I put every adjust send event in background thread also

<img width="506" alt="Screen Shot 2019-08-01 at 16 19 23" src="https://user-images.githubusercontent.com/22385723/62281561-316fda80-b478-11e9-9576-24fcac5dad0d.png">

**Comment by uerceg** [comment]
Hi @Amabella 

You should not be worried about this message. 

In Android in order for SDK to be aware of app being in foreground or background, we are relying on proper user integration of SDK and proper firing of `Adjust.onResume()` and `Adjust.onPause()` calls to SDK. With this information, we can know if app is in foreground or not. If we see `Adjust.onPause()` being invoked with no `Adjust.onResume()` being followed by less than 1 second in between, SDK will start to think that app is not in foreground anymore (this scenario actually happens when app goes out of focus, since `onPause` method of last activity is last method to be invoked). But when user is navigating between different activities what happens is that combo of `onPause()/onResume()` activity calls is happening all the time super fast (less than 1 second in between). This log message simply logs situation when that happens.

So feel free to ignore the message, it's not an error, thus nothing to be fixed.

Cheers
