### ISSUE TITLE
Support for tracking install of Google Play Public Beta Program

### ISSUE THREAD

**Issue by grace40205** [adjust/android_sdk#398]
Hi, 
The problem I met is that **no android installs show up in dashboard.**
- since the "Install tracked" log can be seen in Logcat, SDK integration(4.11.4 used) should be set up right.
- scenario: link clicked -> transit to play store and install app -> launch app(Install supposed to be tracked)

For troubleshooting:

1. I wonder whether Adjust can track installation of public beta apps in Play Store. If beta app install tracking is supported, I could find out if the change of source code led to this issue.
1. ProGuard is open in the app. 
     However instead of the [settings in README](https://github.com/adjust/android_sdk/tree/v4.11.4#proguard-settings), `-keep class com.adjust.**{ *; }` is used. Did this caused the issue?

Thanks.

**Comment by uerceg** [comment]
Hi @grace40205 

Which environment did you set for SDK in that beta release of your app - sandbox or production? In case it's maybe sandbox (assuming since you mention that you see the logs which our SDK outputs in sandbox mode only), are you checking sandbox or production traffic in the dashboard for your app?

Cheers

**Comment by grace40205** [comment]
For release, environment is always set to production.
I just set environment to sandbox temporarily to test if SDK is set up correctly.
I will check the dashboard traffic settings.

Thanks.

**Comment by uerceg** [comment]
Ah, okay. Production is actually default view in dashboard so in case you didn't change anything in there, you're most probably looking at production traffic.

To answer your question from initial comment. Adjust SDK is agnostic towards channels through which app is distributed. So we don't really care if it's debug build that you are testing, the one released to beta Play Store channel or official Play Store release. Only thing we distinguish upon is environment variable.

If you just started to perform this test with your device, what comes up to my mind is that maybe you made an install of your app to your test device while running the SDK in sandbox mode during your tests and that this was the moment in which we have recorded install from your device for given app token. Later, if you uninstalled the app and did scenario with clicking -> transition -> installing again, that would not qualify on our end as an install, since we already know about activity from your device for given app token, regardless of the fact that environment changed.

So if you wanna see install incoming from exactly that device you're testing with, I'd advise you to do following:

1. Uninstall any app version you have on that device.
2. Go to Testing Console in Adjust dashboard and using Google Advertising Id of your device, forget it from our backend.
3. Perform your test flow described in first comment.

After this, if SDK in that beta app version is set to production, install which you make should be seen in your production traffic on dashboard.

**Comment by grace40205** [comment]
Ok, I'll try it out again.
Actually, after uninstall and before re-install, I used the url below to forget the device and install tracking can be seen in Sandbox traffic on dashboard.
> http://app.adjust.com/forget_device?app_token={yourAppToken}&adid={adidValue}

Thank you.

**Comment by uerceg** [comment]
I am pretty sure that URL is not something you can use, but rather you need to use your device's `gps_adid` value and forget your device with it on Testing Console for your app in Adjust dashboard.

**Comment by grace40205** [comment]
Hi, @uerceg 
I'll close this issue. It turns out that **improper ProGuard rule** for Adjust caused **gps_adid could not be sent for install tracking** which caused the problem mentioned in the initial comment.
Thank you.

**Comment by uerceg** [comment]
Thank you for the update!
