### ISSUE TITLE
Android deep_link comes with some extra query parameters

### ISSUE THREAD

**Issue by bulatgaleev** [adjust/android_sdk#401]
Example:
`adjust_deeplink=**myschema**%3A%2F%2F**mypath**`

Giving:
`myschema://mypath?adjust_reftag=XXXXX`

I believe we never receive this **adjust_reftag** before.
I also believe this is something internal info Adjust should handle internally and shouldn't expose.

Adjust versions: **4.17.0**, **4.18.4**

**Comment by uerceg** [comment]
Hi @bulatgaleev 

That mechanism is in place for several years already in our platform. **adjust_reftag** serves as verification mechanism that click on Adjust tracker URL containing deep link information which later opens your app is actually the interaction which drove **sdk_click** later being sent with content of this deep link which might potentially reattribute your user.

As much as we would like to keep this unexposed, there's no possible way since path from clicking the tracker URL to our SDK goes through Android operating system and means we have at our disposal to propagate information from the click to the SDK. And only way is if we put this additional information into URL which you will later see as you mentioned above. It's simply how things work and feel free to ignore that information from the URL you extract from the intent.

In case you have any further questions, feel free to ping.

Cheers

**Comment by tobi512** [comment]
Just ran into the same problem with `adjust_reftag` that breaks our deeplink implementation since the additional parameter is seen as part of the deeplink value as @bulatgaleev describes...
Am I seeing it right that the solution you propose is to manually remove the `adjust_reftag` for the Uri @uerceg?
This seems like a really hacky approach to me.

**Comment by uerceg** [comment]
Hi @tobi512 

You are seeing it right. Like explained above, presence of that parameter in the URL is simply way to verify incoming traffic from our SDK. I understand that it alters URL and also like advised above, currently you can either choose to ignore it (if its presence in there doesn't disturb your URL processing logic) or to simply process URL upon receiving it to remove that parameter which we have appended.

Alternative to this would be for SDK maybe to add some logic which would do this extraction and provide you with URL you placed in your tracker URL which beyond doubt I see how nice would it be for you. We have raised this concern and question with our product team, so we'll see if we can maybe do something about it in the future.

Cheers

**Comment by tobi512** [comment]
Thanks for the quick reply. A generic solution provided by the SDK would be the best way since altering URLs manually is very error-prone in my experience. 
I found a workaround for this issue without changing the URL by defining a second deep link in my navigation graph that contains the "adjust_reftag"-parameter, so it matches and the deep link works when the parameter is present. 

However, this is also kind of a hack and I'd be happy to remove it once the SDK handles the parameter internally...

**Comment by uerceg** [comment]
Good to hear that some workaround was possible in your case. But like said, fully understand your point and we will discuss this topic internally to see how to potentially handle it more gracefully. For now, it simply how system works. Will close the issue for now, but try to ping in here if any decisions on changing this behaviour on our end happen.

Cheers!

**Comment by OlegPanfyorov** [comment]
Hello, @uerceg 
Could you explain me please how can I get params instead of adjust_reftag?

If I'm clicking on next link: 
https://app.adjust.com/ms8lmzu?deep_link=xodev%3A%2F%2Fquizzes&id=12
in my case id (and all other params that I wanna set dynamically) are cropped and replaced with adjust_reftag
<img width="1051" alt="Screenshot 2021-07-19 at 17 36 47" src="https://user-images.githubusercontent.com/5898390/126178731-950e67c6-ff51-48ed-92a9-a093eccb89f0.png">

So I couldn't use these params to go deeper inside the app, create some specific games by id, connect with some people by id or username, etc.

Appreciate if you can help me and explain how can I do this

**Comment by uerceg** [comment]
Hi @OlegPanfyorov 

Sorry for delay on this one. Hm. 🤔 From what I can see in here, seems like the link you're clicking onto (has `deep_link` value set to `xodev://quizzes&id=12`. And what your app seems to be receiving when you're debugging is `xodev://play_kfm`. I'm ignoring `adjust_reftag` parameter since that's what our backend will always attach on URL click and redirection to the store.

In here I see two problems:

1. The fact that I mentioned above -> seems like different deep link arrived into the app than what your URL states. This might be some testing related issue.
2. I am not sure if your tracker URL is properly formatted. Actually that depends on whether your idea was to get `&id=12` inside of the deep link in the app or not. In this way how you wrote it, it's not part of the `deep_link` parameter value because it's not properly encoded for that, but instead it's on same level as `deep_link` parameter and will not arrive into the app. In case you want to see `id=12` being part of deep link inside of the app, tracker URL should look like: https://app.adjust.com/ms8lmzu?deep_link=xxodev%3A%2F%2Fquizzes%26id%3D12.

Back to 1 from above. What are you exactly testing - standard or deferred deep linking scenario?

**Comment by alihossain-dh** [comment]
@uerceg I have one question related to the this. We have a similar situation and cant make the `&id=12` encoded because of  some other reason. Do you know is there any way to get this parameter inside our app activity oncreate as intent or any other way to get it into the app? I want this `id` basically and don't want to make it part of `deep_link` and encrypted.
