### ISSUE TITLE
install referrer api will be deprecated in March 2020

### ISSUE THREAD

**Issue by calvarez-ov** [adjust/android_sdk#406]
We received this mail from Google Play:

> Hello Google Play Developer,
> 
> We recently [announced](https://android-developers.googleblog.com/2019/11/still-using-installbroadcast-switch-to.html) that we’ll be deprecating the install_referrer intent broadcast mechanism. Because one or more of your apps uses this intent to track referrals, we wanted to ensure you make the switch before **March 1, 2020**. After this date, new versions of the Play Store app will no longer broadcast the install_referrer intent after app installs.
> 
> Action required
> 
> [Migrate to the Play Install Referrer API](https://developer.android.com/google/play/installreferrer/library.html) to track your app installs for the following apps and/or games.
> 
> The Play Install Referrer API offers better performance, uses a secure communication channel between your app and the Play Store, and offers a more robust solution against spoof and attribution fraud.
> We know this change may require some additional work on your part and appreciate your understanding.

Looks like adjust sdk may need some update to use the new api.

If I'm mistaken and adjust is already using the new api, sorry for the noise.  I wasn't sure because the adjust readme seems to have info about the new api and old mechanism.

* Old way: adding a broadcast receiver https://github.com/adjust/android_sdk#qs-gps-intent
* New way: using the google play referrer api: https://github.com/adjust/android_sdk#qs-gpr-api

**Comment by uerceg** [comment]
👋 @calvarez-ov 

Adjust SDK updated to work with new install referrer API since [2 years ago](https://github.com/adjust/android_sdk/blob/master/CHANGELOG.md#version-4120-13th-december-2017). Actually [issue](https://github.com/adjust/android_sdk/issues/402) you were commenting on was due to the fact that we are using this API and library got a buggy update. :)

Nevertheless, having in mind you experienced issues with that `1.1` release of install referrer library is a solid indicator that you're using Adjust SDK version which supports it, so you should be fine with it.

One thing you can do in your app as part of spring cleanup when Google sunsets `INSTALL_REFERRER` intent approach for delivering referrer information into app is that you can remove references to `AdjustReferrerReceiver` like we describe in [this chapter](https://github.com/adjust/android_sdk#qs-gps-intent) since that's the mechanism which is now being replaced by new install referrer API.

And just to mention that `AdjustReferrerReceiver` can also be used for tracking preinstall campaigns, so if you're using it for this purpose in your apps, then don't remove it, of course. But if it's declared in your app just for referrer obtaining purposes, it should be safe to be removed.

In case you have any further questions, feel free to ping.

Cheers

**Comment by calvarez-ov** [comment]
Regarding the preinstall campaigns, are you referring to the [Pre-installed trackers](https://github.com/adjust/android_sdk/blob/master/README.md#af-pre-installed-trackers) setup, or something else?

Thanks!

**Comment by uerceg** [comment]
That's the way to run them with SDK API. I was referring to [something like this](http://help.adjust.com/tracking/attribution/pre-install-campaigns).

**Comment by calvarez-ov** [comment]
Ok. Many thanks for the detailed responses!

**Comment by uerceg** [comment]
In case anything else needed on this on, feel free to reopen it. Cheers.
