### ISSUE TITLE
How can i create track event (key, value) on app android

### ISSUE THREAD

**Issue by khanhpt19** [adjust/android_sdk#423]
Hi everyone! 
I'm using Adjust for tracking event when user click on title of document, i want send title of document to adjust dashboard. 
I'm done setup sdk on app and using sandbox mode.
How method can i use to do this?
I tried create new event on adjust dashboard, and using this:
```
AdjustEvent adjustEvent = new AdjustEvent("abc123");
Adjust.trackEvent(adjustEvent);
```
but it only show click count, not show title of document.

Thanks for reading. My english isn't good :(

**Comment by uerceg** [comment]
Hi @khanhpt19 

For this type of questions, I think the best would be to either write email to your dedicated account manager or to support@adjust.com because they might be able to assist you with setting up the flow to achieve what you are trying to do. I don't think you're actually able to do what you're planning to in that form, because dashboard will not dynamically show fields you might attach to event you're tracking. But like said, try pinging support since they might provide you with a workaround which might suit you well.

Cheers.

**Comment by khanhpt19** [comment]
I found this https://github.com/adjust/android_sdk#event-parameters.
I guess in my case, i can using:
`adjustEvent.addCallbackParameter("key", "value");
`
or 
`adjustEvent.addPartnerParameter("key", "value");
`
Did you use them?

**Comment by uerceg** [comment]
If set, those key-value pairs are gonna be appended to callback URL you set in the dashboard which should be triggered when given event was tracked (usually callback to your backend so that we ping you with this information, or callback from some partner network). This information is never even stored on our end, it's just used to be appended to callback URL before pinging it (so nothing which you can see in dashboard or anything like that).

**Comment by khanhpt19** [comment]
Thank @uerceg
