### ISSUE TITLE
Avoid reflection and possible api breakage 

### ISSUE THREAD

**Issue by Shusshu** [adjust/android_sdk#439]
Could you depend on the google play api install referrer directly instead of doing reflection?
https://github.com/adjust/android_sdk/blob/master/Adjust/sdk-core/src/main/java/com/adjust/sdk/InstallReferrer.java#L177

**Comment by uerceg** [comment]
Hi @Shusshu 

We could and that would beyond doubt be easiest way for us to handle this dependency, but our SDK is not built exclusively for apps which run in Play Store and for which this functionality makes sense, but also for Android apps which are distributed outside of Play Store and for which install referrer API doesn't really make any sense. And with direct dependency to it, we would be forcing clients who don't need this feature to import this dependency as well to their apps and this is something history showed us quite a few clients are not really willing to do. For various reasons, amongst most common one - they don't want to increase DEX count any more than really needed.

**Comment by Shusshu** [comment]
Hi, you have valid points but this can be achieved by providing an extra
artifact that would be considered a plugin in order to please all customers

**Comment by uerceg** [comment]
Hi @Shusshu 

And sorry for pretty delayed comment from my end. Also true what you say, but probably not something we will do because, even though it sounds reasonable, past experience showed us that more often than one would expect, clients just tend to ignore README and documentation and make random assumptions on APIs meaning and functionality and I am sure if we would split this, same would go for Maven artefacts.

For now it remains as it is, but we'll address this internally one more time to see if it makes sense for us to go with direct API referencing.

Thanks one more time for the comments.

Cheers
