### ISSUE TITLE
oaid sdk update 1.0.22

### ISSUE THREAD

**Issue by qtfreet00** [adjust/android_sdk#450]

**Comment by ugi** [comment]
Hi @qtfreet00 

Today we have released the SDK v4.23.0 update and OAID plugin got updated in there to be compatible with MSA SDK v1.0.13 (and hopefully later) because they have introduced breaking changes in that version for some reason.

Did you try latest version of OAID plugin? If not, please give it a shot and let us know if it worked for you.

Cheers

**Comment by ugi** [comment]
If needed, feel free to reopen/comment.
