### ISSUE TITLE
Safely call Adjust.getAdid()

### ISSUE THREAD

**Issue by Perick95** [adjust/android_sdk#454]
Hi!
I'm trying to retrieve the adjust identifier inside my application but sometimes this method return null.
There is a way to call this method safely? 
Why you don't manage the adjust id in the same way you have managed the Google Play Advertising ID? Here the example:
`Adjust.getGoogleAdId(applicationContext, OnDeviceIdsRead {gaid ->
            // here the GoogleAdIs is not null
        })`

Thanks in advance.

**Comment by ugi** [comment]
Hi @Perick95 

`adid` is Adjust identifier for the device and a thing which is generated on our backend. In order for SDK to get in possession of this parameter, it needs to be initialised at least once and after initialisation to send session request to our backend. Upon this request, SDK obtains this value and from that moment on, this getter will start to return actual value of it and not null.

Also legit question from your end. Historically we made this getter to be synchronous and it's been like that ever since. Reason why Google Advertising ID getter is asynchronous is because native API for reading Google Advertising ID is also asynchronous and when ever you invoke SDK's getter for it, we're simply forwarding this call under the hood to native API.

But definitely I agree that it makes sense that `adid` getter works in same way and actually that is how it will work in our next major SDK release.

While still in v4, you can actually detect a moment in which this value stops to be `null` and that's if you implement [session tracking success/failure callbacks](https://github.com/adjust/android_sdk#af-session-event-callbacks) and as soon as one of these gets pinged for the first time ever (this is indicator that above mentioned session request has completed), that marks the moment in which our SDK got `adid` value and from that moment on `getAdid()` should always return that value.

In case you have any further questions, feel free to ping.

Cheers

**Comment by Perick95** [comment]
Hi @ugi 

Thanks for your quick reply and the clarification about the Adjust identifier and how it's work. I implemented as you said using the session tracking callbacks and i'm waiting the future releases of the SDK.

Cheers  :)

**Comment by Perick95** [comment]
Hey @ugi 

I'm here again 😅 I've implemented the `getAdid()` as you said inside the `OnSessionTrackingSucceededListener` and it works correctly. What is not clear to me is when this listener is triggered; I thought it is whenever the SDK is initialized (and the session starts) but it seems that the listener is triggered only on the first installation of the app and not on every reopen of the application. 

Probably I have no clear your definition of session inside the app and the dashboard, it seems that there is a single session until the user uninstall the app or clear the app storage.

Thanks for the availability.

**Comment by ugi** [comment]
Hey @Perick95 

Sorry for a bit of delay in response.

SDK being initialised and session start are not necessarily happening at the same time. New session in SDK (if we exclude first one which is being fired automatically when SDK is initialised for the first time ever) will be fired when your app enters foreground again if it was not in foreground for 30+ minutes.

So suggestion I made above was pretty much to use session callbacks only to get **adid** value as soon as possible and as indicator that from that moment on, it is safe to use **getAdid()** getter. Like said, not the greatest mechanism in v4, will be made better in v5, but for now that's how it works. For example, you can simply store some boolean in shared preferences in the moment when you obtained **adid** for the first time in one of two session callbacks and from that moment on, use that boolean as indicator to know that it's safe to invoke getter (random suggestion, not sure if it makes any sense in your app).

Cheers
