### ISSUE TITLE
question: event tracking for a hybrid app

### ISSUE THREAD

**Issue by 2jiwon** [adjust/android_sdk#488]
Hello, I am going to install this SDK for a hybrid app.
However, I am not sure how to track all the events in my application.
What I read is I need to make tokens for every event's points that I want to track, then send to Adjust by using ``Adjust.trackEvent()``.  But should I do this for every events individually?
Usually, I just made an Interface that communicates with the web view, and then just send data from the web to my application.
So, do I need to manage this part, or are there any APIs for this kind of job?

**Comment by uerceg** [comment]
Hi @2jiwon 

And sorry for delay in replying on this one. Sounds to me that you can in theory use one of two approaches with Adjust SDK - you can either use our SDK with web bridge (our custom built plumbing for propagating stuff from web views to native SDK) or, having in mind that you already have your custom messaging mechanism between web views and native layer, you might be able to just use native Android SDK and if event tracking is only thing you plan to do, find a way to pass information from web view to native part and track those natively with the SDK.

I'd suggest to go with web bridge approach since it's gonna be more friendly towards your hybrid app since it already offers JavaScript API for communicating with the SDK and you can use it directly from your web views.

In case you have any other questions, feel free to ping.

Cheers
