### ISSUE TITLE
Adjust.getAdid() returning `null` after Adjust.onCreate(config)

### ISSUE THREAD

**Issue by nzakharchenko** [adjust/android_sdk#496]
Hey there!

We have an issue of getting `adid` by using `Adjust.getAdid()` just after we initialised the SDK.

Initialisation is done in default way:

```
val config = AdjustConfig(context, {token_here}, {environment_here}, true)
config.setAppSecret(.......)
Adjust.onCreate(config)
```

and if just after this piece of code we call  `Adjust.getAdid()` - result would be always `null`. 
But some time later `adid` will actually appear. So my assumption is that there is some async operation happening. Therefore I have a question if there is any call back where I could be sure that `adid` would be present?

SDK version - 4.25.0

Thx in advance!

**Comment by uerceg** [comment]
Hi @nzakharchenko,

I'd say that you should most probably find all your answers in here: https://github.com/adjust/android_sdk/issues/454.

In case you have any further questions, feel free to ping.

**Comment by nzakharchenko** [comment]
@uerceg thank you for quick answer!
I have tried to add all 4 available listeners (as mentioned in documentation). But that works only on the first app install. On the second run non of that listeners are fired :(. The same issue mentioned here https://github.com/adjust/flutter_sdk/issues/34#issuecomment-772586742. Any suggestion how to solve it in the nice way?

**Comment by uerceg** [comment]
Event callbacks are gonna get fired when you attempt to track event (so pretty much when you make a call to `Adjust.trackEvent` and when SDK attempts to make HTTP request for that event). Session callbacks are fired in same fashion when SDK tries to make HTTP request to send session package to our backend (session tracking is autonomous process fully in power of SDK is integration is properly done on client side and you can't influence it). Upon initial SDK launch in app, SDK will by default track first session package (install). For that you will be informed whether it succeeded or failed. This is the callback trigger you see upon SDK launch after installing an app. If you close an app and reopen it, you're not gonna see this callback fired again because session is defined as app foregrounding after being outside of foreground for 30+ minutes. But in theory, this should not be that important because (as written in those tickets), once you receive first session success callback, that's the moment in which install for your user has been tracked, `adid` got generated on backend side and communicated back to SDK which has it locally stored from that moment on and any subsequent call to `Adjust.getAdid()` should return `adid` value instead of `null`.

**Comment by nzakharchenko** [comment]
@uerceg thx a lot for so detailed explanation. 
Just to clarify one more point. Once SDK got back from backend the `adid` - it gets written to the file, am I correct? And if I put app to background (or basically even kill it from the recents) and then run again - SDK will take `adid` from the file, am I correct?
Because somehow, for me, even after the second (and all following) app openings I still get `null` for some time. And actual `adid` appears later.

As a solution, I am planning to save it to shared prefs locally and use it - would it be fine to save `adid` locally from your perspective?

**Comment by uerceg** [comment]
> Just to clarify one more point. Once SDK got back from backend the adid - it gets written to the file, am I correct? And if I put app to background (or basically even kill it from the recents) and then run again - SDK will take adid from the file, am I correct?

That is correct.

> Because somehow, for me, even after the second (and all following) app openings I still get null for some time. And actual adid appears later.

Did you implement [session tracking](https://github.com/adjust/android_sdk#qs-session-tracking) in your app as advised in the README? Where are you making a call to `Adjust.onCreate` method - is it like README advises (`onCreate` method of `Application` class) or is it later in some activity?

> As a solution, I am planning to save it to shared prefs locally and use it - would it be fine to save adid locally from your perspective?

SDK keeps this locally stored in some of the files we're keeping internal information in, so in theory you doing the same with shared preferences should not be needed. Question is to demystify what makes you occasionally get `null` value since that should not be happening.

**Comment by nzakharchenko** [comment]
@uerceg yeah, we are doing session tracking like it is described in documentation. And we call `Adjust.onCreate` in the `onCreate` of `Application`.

But still, on the second run I am getting `null` with such code
```
Adjust.onCreate(config)
Timber.i("# Adjust.getAdid() -> ${Adjust.getAdid()}")
```

```
# Adjust.getAdid() -> null
```

Any ideas why that could happen?

**Comment by uerceg** [comment]
Can you send verbose sandbox logs from first and second run? Feel free to omit any sensitive data from the logs.

**Comment by lukas2606** [comment]
> Hey there!
> 
> We have an issue of getting `adid` by using `Adjust.getAdid()` just after we initialised the SDK.
> 
> Initialisation is done in default way:
> 
> ```
> val config = AdjustConfig(context, {token_here}, {environment_here}, true)
> config.setAppSecret(.......)
> Adjust.onCreate(config)
> ```
> 
> and if just after this piece of code we call  `Adjust.getAdid()` - result would be always `null`. 
> But some time later `adid` will actually appear. So my assumption is that there is some async operation happening. Therefore I have a question if there is any call back where I could be sure that `adid` would be present?
> 
> SDK version - 4.25.0
> 
> Thx in advance!

**Comment by nzakharchenko** [comment]
> Can you send verbose sandbox logs from first and second run? Feel free to omit any sensitive data from the logs.

Here is logs:

[fresh_start.txt](https://github.com/adjust/android_sdk/files/6763428/fresh_start.txt)
[second_start.txt](https://github.com/adjust/android_sdk/files/6763425/second_start.txt)

Let me know if that helps somehow.

**Comment by uerceg** [comment]
Hi @nzakharchenko 

And sorry for a delay on this one. I think I can assume what's up in here. I think you're just calling `getAdid()` method too soon. Lemme explain what's happening behind the scenes.

Seems like you're just firing `Adjust.onCreate(config);` and then `Adjust.getAdid();` calls one after another. `onCreate` method once initialised it will cause SDK to initialise, which is not immediate process, it takes some time for it to be completely finished. In your first run, `getAdid()` will for sure return `null` because SDK needs to initialise + create install session packed + send it to backend + get the response from the backend that install has been tracked. Only after that sequence, SDK is becoming aware of `adid` value and `getAdid()` getter will be able to return it. But in your 2nd run, calling `getAdid()` right after `onCreate` method is causing those two paths to race (and unfortunately `getAdid()` will win which is not what you want to see). When `onCreate` is called on 2nd run, upon initialisation SDK will need to load `adid` value from activity state file (which we have stored inside of the bundle and in which `adid` value is persisted) into memory from where `getAdid()` method will try to read it. And your super fast invocation of `getAdid()` right after `Adjust.onCreate` method causes still unpopulated `adid` in memory value to be read (because it takes some time for file to be read), thus the null value.

We are aware that this is not the greatest behaviour (to have synchronous `getAdid()` method) because there's obviously hidden internal SDK logic you need to be aware of in order to properly use this getter. We're actually changing this and are planning to make all of our getters asynchronous in SDK v5, but for time being, this is how things are going to remain in SDK v4 due to our non breaking API changes within the same major version policy.

In case you have any further questions on this topic, feel free to ping us.

**Comment by uerceg** [comment]
In case you have additional questions, feel free to comment/reopen. Cheers.
