### ISSUE TITLE
Doc should mention Adjust.onResume() prerequisite for event tracking

### ISSUE THREAD

**Issue by AnwarShahriar** [adjust/android_sdk#530]
My team was implementing Adjust for android  by following the `README.md` and we avoided session tracking setup as we only wanted to track revenue event only. 

Later we realized by trial and error that without setting up session tracking (`Adjust.onResume()` and `Adjust.onPause()` with activity lifecycle), the event tracking doesn't work at all.

The Github `README.md` event tracking section doesn't mension that we must implement session tracking to make it work. Updating the doc would be super helpful, let me know if I should open up a PR to do that or we're doing something entirely wrong here.

**Comment by shashanksu** [comment]
Hi @AnwarShahriar ,
Our [docs](https://help.adjust.com/en/article/get-started-android-sdk) already have separate sections for Optional setup, additional features etc.  And since session tracking is part of Getting started with the Android SDK steps, it is implicit.  Hope this helps, closing this one.
Thanks
