### ISSUE TITLE
All installs are attributed to Organic

### ISSUE THREAD

**Issue by 42thcoder** [adjust/android_sdk#570]
We use the tracker url to promote the app. The link is like this: via https://app.adjust.com/xxxx?campaign=Reddit&adgroup=TestGroup it goes to Google Play, the user installs and downloads, and then I guess the Adjust SDK will After that I guess the Adjust SDK will get https://app.adjust.com/xxxx?campaign=Reddit&adgroup=TestGroup from Google Play via install refer and report it to Adjust's server.

Eventually we see an  install data in the Adjust backend, attributed to Reddit. 

The problem is that all the installs are attributed to Organic. We're not sure if it's a configuration issue with Adjust or Google Play, or if it's a coding issue.

We look forward to hearing from you!

**Comment by religofsil** [comment]
we've got the same issue, did you figure it out?

**Comment by uerceg** [comment]
Hey guys, sorry for delay.

> Eventually we see an install data in the Adjust backend, attributed to Reddit.
>
> The problem is that all the installs are attributed to Organic.

@42thcoder ☝️ Can you maybe clarify this a bit to me? Do you see any installs in your dashboard being attributed to `Reddit` campaign of the `xxxx` tracker or are all the installs attributed to `Organic` tracker?

Matching click to an install is pretty much part of the overall campaign setup (creating proper tracker URLs, configuring things in dashboard and running the campaign). SDK is of course part of the flow, but for this particular thing, only thing which SDK needs to do is to track install (which seems like it's doing for you because you do see installs being tracked in dashboard regardless of the tracker they are attributed to) and to be able to pass information about Android install referrer to our backend.

When you run the test install of your app with Adjust SDK inside (you can set environment to sandbox and log level to verbose for accessing all the logs), can you check if SDK is sending package called `sdk_click` with parameter inside `source=install_referrer`?

**Comment by shashanksu** [comment]
Hi @42thcoder,
Closing this as there are no further update on this one.  In case you still have this issue, please get back.
Thanks
