### ISSUE TITLE
adjust-android-samsung-referrer error

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [adjust/android_sdk#572]
InstallReferrerClient in adjust-android-samsung-referrer is under package com.sec.android.app.samsungapps.installreferrer.api. The InstallReferrerClient in store.galaxy.samsung.installreferrer is under com.sec.android.app.samsungapps.sinstallreferrer.api, which leads to compilation error in the official version of the package. I am using version 4.33.3 of adjust, samsungapps installreferrer related documentation seems to say that you need to use version 4.33.4, but I can't pull 4.33.4, android studio says it doesn't exist.

**Comment by shashanksu** [comment]
hi @AndroidJohnsonWang 

Thanks for reaching out.  Yes, due to non-backward compatibility nature of Samsung Install Referrer library, there's this discrepancies.  We intend to release Android SDK 4.33.4 soon (not yet released).  So for now, please reach out to Samsung representative (as mentioned in our doc) and ask for the older version of Samsung Install Referrer library offline AAR file, which is supported by our SDK version 4.33.3.  Meanwhile, we will be releasing the version 4.33.4, which do support the current version of Samsung Install Referrer library and the issue you observed should ideally no more be seen.  

Hope this helps.  In case you have any further queries/concerns, please do mention. 

Thanks
Shashank

**Comment by shashanksu** [comment]
hi @AndroidJohnsonWang 
We have released Android Adjust SDK version 4.33.4 now.  This should resolve your issue.  Closing it, please feel free to reopen in case still you see any issue, thanks!
