### ISSUE TITLE
Hi, Adjust team. I want to integrate adjust sdk for our android app, but there is a question.

### ISSUE THREAD

**Issue by EysaDun** [adjust/android_sdk#586]
We want to know how many users installed and opened our app, is it easy to know after integrated adjust sdk?
And, I viewed adjust sdk tutorial but don't found witch method should be invoke, maybe, it's automatically.

**Comment by uerceg** [comment]
Hi @EysaDun,

Those numbers are being shown on the Adjust dashboard and it's not something which SDK offers any API for you to get. In order to see that, you need to be signed up to use Adjust, have an app created on the dashboard and then once you have set up the SDK in your app, you will be able to see all the stats in the dashboard.

In case you have any further questions, feel free to ping.

**Comment by uerceg** [comment]
Closing this one, but if you have any further questions, feel free to comment / reopen. Cheers.
