### ISSUE TITLE
Don't fail SDK initialization when signer is absent

### ISSUE THREAD

**Issue by G00fY2** [adjust/android_sdk#616]
With v5 there was a check added which prevents Adjust initialization if the signer is not found: 17deacd13c1c26e88e2a2fee2a8bc5e55d026283

This basically prevents people, who do not use the SDK Signature, from using Adjust without adding the quiet large native libsigner.so (by excluding `adjust-android-signature` via Gradle).

This check is also not necessary, because the signerInstance is still optional and the same null check like in v4 are present: https://github.com/adjust/android_sdk/blob/c0f78d2ec77dfacbf53870883b9d5b0e6ca8c731/Adjust/sdk-core/src/main/java/com/adjust/sdk/AdjustSigner.java#L47

We would therefore like you to remove the early return from 17deacd13c1c26e88e2a2fee2a8bc5e55d026283. The warning should be sufficient and the SDK should just work fine.

**Comment by shashanksu** [comment]
Hello @G00fY2,

Thanks for sharing your feedback & concern.  To confirm, the check to prevent from not using of SDK Signature is intentional.  Considering the fraud landscape, we’ve made a product decision to couple main SDK with Signature library more tightly starting in v5.  In the future, you may see tighter dependencies of main SDK with the Signature library.  However the actual signature enforcement is a feature you can control through the dashboard.

Also, about your concern for the size, we will respond and can further discuss in your [relevant issue](https://github.com/adjust/android_sdk/issues/617).

Hope this clarifies a bit.  Please let us know if you still have any other concern(s).

Best regards

**Comment by G00fY2** [comment]
Thank you very much for the detailed answer! So you enforce shipping the native Signature SDK even though this feature is optional and `inactive by default` as still stated in the v5 migration guide, right? 
I assume you try preventing consumers running into issues when they deciding to turn on signature enforcement in the dashboard later on. I can see the idea behind that and it probably makes sense.

We actually would like to prevent bloating our app size and minimize potential runtime overhead for the obsolete signing.

Maybe you can come up with smaller native Signer library in the future (as requested in #617) to lower our pain about app size. And also maybe in the future we decide to actually enable signature enforcement, so we have to execute the signing code.

So feel free to close this ticket.

Best regards.

**Comment by shashanksu** [comment]
Appreciate your understanding on this.  Thanks for your suggestion, we definitely continue to look into all possibilities of reducing the size of native Signer library.  Further discussion on this in #617.

Closing this ticket.  Thank you.
