### ISSUE TITLE
Unable to get Google Play Services Advertising ID at start time

### ISSUE THREAD

**Issue by FGoetzAS24** [adjust/android_sdk#68]
In PRODUCTION mode the SDK does not receive the Google Play Services Advertising ID, so it is not possible to track a session.

09-18 14:24:06.304    3262-3317/? A/Adjust﹕ PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to `sandbox` if you want to test your app!
09-18 14:24:06.324    3262-3317/? I/Adjust﹕ Unable to get Google Play Services Advertising ID at start time
09-18 14:24:06.334    3262-3317/? I/Adjust﹕ First session
09-18 14:24:06.774    3262-3322/? E/Adjust﹕ Failed to track session. (Missing device identifiers)

**Comment by alvarosantisteban** [comment]
Hi,
I just tested the app for the first time and I am receiving the following messages:

`I/Adjust﹕ SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to production before publishing!`

`I/Adjust﹕ Unable to get Google Play Services Advertising ID at start time`

`I/Adjust﹕ Install tracked`

I am not sure if it is correctly set or not. The Proguard file contains the three lines of your guide.

**Comment by uerceg** [comment]
Hi @alvarosantisteban 

Well, depends wether you want Google Play Services integrated in your app or not. This Info message in Adjust logs just says that our SDK didn't find Google Play Services (or at least Google Play Services Adds part) integrated in your app. Having in mind that install was successfully tracked, you have set up the adjust SDK properly.

If you want to see more logs from our SDK (which can be useful while testing), set `log level` on `adjust config instance` to `VERBOSE`. Info about how to do that you can find in here: https://github.com/adjust/android_sdk/blob/master/README.md#adjust-logging

And in case you want to integrate Google Play Services so that our SDK doesn't report this message from above, you should check how to do that in here: https://github.com/adjust/android_sdk/#4-add-google-play-services

If you have any other questions, feel free to ask.

Cheers

**Comment by alvarosantisteban** [comment]
Thanks, I will ask the client :)
