### ISSUE TITLE
Adjust Singleton difficult to test

### ISSUE THREAD

**Issue by joecks** [adjust/android_sdk#80]
The Adjust Sigelton only provides static methods, which is just possible to mock with PowerMock, but this is not working with robolectric. So I suggest to move the Adjust Singleton implementation to a class 
AdjustImpl which is instantiated statically and exposed with getInstance and setIntance to clients, so it is possible to mock its behavior.

**Comment by nonelse** [comment]
The [AdjustInstance.java](https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/AdjustInstance.java) file allows to create different instance of the adjust interface. Take notice that it should be only used for testing, because stuff like the Install Referrer still uses the default static `Adjust` interface
